/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.comercial.compra;

import gui.financeiro.CondicaoPagamento.PesquisarCondicaoPagamento;
import gui.modeltable.TableModelContas;
import gui.modeltable.TableModelItemProduto;
import gui.modeltable.TableModelParcelaSimples;
import gui.modeltable.TableModelProduto;
import gui.pessoas.fornecedores.PesquisarFornecedor;
import gui.produtos.PesquisarProduto;
import gui.swing.DialogPadrao;
import gui.swing.SwingFormatterFactory;
import jdk.nashorn.internal.scripts.JO;
import lib.model.comercial.Compra;
import lib.model.comercial.ContaPagar;
import lib.model.comercial.ItemProduto;
import lib.model.financeiro.parcela.Parcela;
import lib.model.interno.ModuloSistema;
import lib.model.interno.NivelAcessoModulo;
import lib.model.pessoa.fornecedor.Fornecedor;
import lib.service.CompraService;

import javax.mail.FetchProfile;
import javax.swing.*;
import javax.swing.text.html.Option;
import java.awt.*;
import java.util.*;
import java.util.List;

/**
 * @author Diego
 */

public class CadastroCompraForm extends DialogPadrao {

    private Compra compra;
    private ItemProduto itemProdutoSelecionado;
    private List<ItemProduto> itens;
    private TableModelItemProduto tableModelProduto;
    //   private TableModelParcelaSimples tableModelParcelaSimples;
    private TableModelContas tableModelContas;
    private List<ContaPagar> contas;

    /**
     * Creates new form CadastroCompraForm
     */
    public CadastroCompraForm(Window parent, boolean modal, Compra compra) {
        super(parent, modal, ModuloSistema.FINANCEIRO, NivelAcessoModulo.LEITURA_GRAVACAO);
        itens = new ArrayList<>();
        initComponents();
        this.compra = compra;
        tableModelProduto = new TableModelItemProduto();
        tableModelContas = new TableModelContas();
        contas = new ArrayList<>();
        // this.tblItens.setModel(tableModelProduto);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        edtFuncionario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lblDescricaoForm = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        edtDtChegada = new com.toedter.calendar.JDateChooser();
        edtDtEmissão = new com.toedter.calendar.JDateChooser();
        edtModeloNota = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItens = new javax.swing.JTable();
        btnAlterarFornecedor = new javax.swing.JButton();
        btnAlterarFornecedor.setContentAreaFilled(false);
        btnAlterarFornecedor.setOpaque(true);
        btnAlterarFornecedor.setBackground(Color.white);
        edtFornecedor = new javax.swing.JTextField();
        btnRemoverItem = new javax.swing.JButton();
        btnRemoverItem.setContentAreaFilled(false);   btnRemoverItem.setOpaque(true);   btnRemoverItem.setBackground(Color.white);
        btnAlterarItem = new javax.swing.JButton();
        btnAlterarItem.setContentAreaFilled(false);   btnAlterarItem.setOpaque(true);   btnAlterarItem.setBackground(Color.white);
        edtNumeroNota = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        edtNumeroSerie = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        edtCodFornecedor = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblContasApagar = new javax.swing.JTable();
        lblDescricaoForm1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        edtCondicaoPagamento = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnAltCondicao = new javax.swing.JButton();
        btnAltCondicao.setContentAreaFilled(false);
        btnAltCondicao.setOpaque(true);
        btnAltCondicao.setBackground(Color.white);
        jLabel20 = new javax.swing.JLabel();
        edtCodProduto = new javax.swing.JFormattedTextField();
        edtNome = new javax.swing.JTextField();
        btnPesquisarItem = new javax.swing.JButton();
        btnPesquisarItem.setContentAreaFilled(false);
        btnPesquisarItem.setOpaque(true);
        btnPesquisarItem.setBackground(Color.white);
        edtUnMedida = new javax.swing.JTextField();
        edtQuantItem = new javax.swing.JFormattedTextField();
        edtValorItem = new javax.swing.JFormattedTextField();
        edtDescItem = new javax.swing.JFormattedTextField();
        edtAcrescUn = new javax.swing.JFormattedTextField();
        edtCustoProduto = new javax.swing.JFormattedTextField();
        btnAddItem = new javax.swing.JButton();
        btnAddItem.setContentAreaFilled(false);   btnAddItem.setOpaque(true);   btnAddItem.setBackground(Color.white);
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        edtTotalDescontos = new javax.swing.JFormattedTextField();
        edtTotalAcrescimos = new javax.swing.JFormattedTextField();
        edtCustoTotal = new javax.swing.JFormattedTextField();
        edtCodCondicaoPagamento = new javax.swing.JFormattedTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        edtValorSeguro = new javax.swing.JFormattedTextField();
        edtValorFrete = new javax.swing.JFormattedTextField();
        jFormattedTextField4 = new javax.swing.JFormattedTextField();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nova compra");
        setResizable(false);

        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancelar.setText("cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSalvar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSalvar.setText("salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        edtFuncionario.setEditable(false);
        edtFuncionario.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Funcionario");

        lblDescricaoForm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDescricaoForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shoppingcart_to_compra_12829 (1).png"))); // NOI18N
        lblDescricaoForm.setText("Nova compra");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        edtModeloNota.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jScrollPane1.setViewportView(tblItens);
        if (tblItens.getColumnModel().getColumnCount() > 0) {
            tblItens.getColumnModel().getColumn(0).setPreferredWidth(5);
            tblItens.getColumnModel().getColumn(1).setPreferredWidth(25);
            tblItens.getColumnModel().getColumn(2).setPreferredWidth(10);
            tblItens.getColumnModel().getColumn(3).setPreferredWidth(10);
            tblItens.getColumnModel().getColumn(4).setPreferredWidth(10);
            tblItens.getColumnModel().getColumn(5).setPreferredWidth(10);
        }

        btnAlterarFornecedor.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnAlterarFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pesquisar.png"))); // NOI18N
        btnAlterarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarFornecedorActionPerformed(evt);
            }
        });

        edtFornecedor.setEditable(false);
        edtFornecedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edtFornecedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                edtFornecedorFocusLost(evt);
            }
        });
        edtFornecedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtFornecedorKeyPressed(evt);
            }
        });

        btnRemoverItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/erro_icon.png"))); // NOI18N
        btnRemoverItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverItemActionPerformed(evt);
            }
        });

        btnAlterarItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit_modify_icon-icons.com_72390.png"))); // NOI18N
        btnAlterarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarItemActionPerformed(evt);
            }
        });

        edtNumeroNota.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        edtNumeroNota.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Serie da nota *");

        edtNumeroSerie.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        edtNumeroSerie.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nm da nota *");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Modelo da nota *");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Data de emissão *");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Data de chegada *");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Código *");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Fornecedor *");

        edtCodFornecedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edtCodFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtCodFornecedorActionPerformed(evt);
            }
        });

        tblContasApagar.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tblContasApagar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblContasApagar.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(tblContasApagar);

        lblDescricaoForm1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDescricaoForm1.setText("Parcelas");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Condição de pagamento");

        edtCondicaoPagamento.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Total de descontos");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("total do acresimo");

        btnAltCondicao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pesquisar.png"))); // NOI18N
        btnAltCondicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltCondicaoActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Valor Total");

        edtCodProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edtCodProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtCodProdutoActionPerformed(evt);
            }
        });

        edtNome.setEditable(false);
        edtNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${itemProdutoSelecionado.nome}"), edtNome, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        edtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtNomeActionPerformed(evt);
            }
        });

        btnPesquisarItem.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnPesquisarItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pesquisar.png"))); // NOI18N
        btnPesquisarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarItemActionPerformed(evt);
            }
        });

        edtUnMedida.setEditable(false);
        edtUnMedida.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edtUnMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtUnMedidaActionPerformed(evt);
            }
        });

        edtQuantItem.setFormatterFactory(  SwingFormatterFactory.buildNumeroReal(0D, null));
        edtQuantItem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edtQuantItem.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                edtQuantItemPropertyChange(evt);
            }
        });

        edtValorItem.setFormatterFactory(  SwingFormatterFactory.buildMoeda(0D, null));
        edtValorItem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${itemProdutoSelecionado.valor}"), edtValorItem, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        edtValorItem.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                edtValorItemPropertyChange(evt);
            }
        });

        edtDescItem.setFormatterFactory(  SwingFormatterFactory.buildMoeda(0D, null));
        edtDescItem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${itemProdutoSelecionado.descontoUnitario}"), edtDescItem, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        edtAcrescUn.setFormatterFactory(  SwingFormatterFactory.buildMoeda(0D, null));
        edtAcrescUn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${itemProdutoSelecionado.acrescimoUnitario}"), edtAcrescUn, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        edtAcrescUn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                edtAcrescUnFocusLost(evt);
            }
        });

        edtCustoProduto.setEditable(false);
        edtCustoProduto.setFormatterFactory(  SwingFormatterFactory.buildMoeda(0D, null));
        edtCustoProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${itemProdutoSelecionado.valorTotal}"), edtCustoProduto, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        btnAddItem.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnAddItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CertoIcon.png"))); // NOI18N
        btnAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Código");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Produto");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Und");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Qtd");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Custo UN");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Desc UN");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Acresc. UN");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Custo");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setText("Editar item");

        edtTotalDescontos.setEditable(false);
        edtTotalDescontos.setFormatterFactory(  SwingFormatterFactory.buildNumeroReal(0D, 1000000D)
        );
        edtTotalDescontos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        edtTotalAcrescimos.setEditable(false);
        edtTotalAcrescimos.setFormatterFactory(  SwingFormatterFactory.buildMoeda(0D, 100000000D)
        );
        edtTotalAcrescimos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        edtCustoTotal.setEditable(false);
        edtCustoTotal.setFormatterFactory(  SwingFormatterFactory.buildMoeda(0D, null));
        edtCustoTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("Tipo frete");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("Valor frete");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("Outras despesas");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("Valor seguro");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton1.setText("CIF");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton2.setText("FOB");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel10))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(edtCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnPesquisarItem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(edtUnMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(edtQuantItem, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(edtValorItem, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(edtDescItem, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(edtAcrescUn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(edtCustoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnAlterarItem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnRemoverItem, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(edtNumeroNota, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(11, 11, 11)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1)
                                .addComponent(edtNumeroSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3)
                                .addComponent(edtModeloNota, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6)
                                .addComponent(edtCodFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(edtFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnAlterarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(12, 12, 12))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(edtDtEmissão, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(edtDtChegada, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(lblDescricaoForm1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addGap(211, 211, 211))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(edtCodCondicaoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(edtCondicaoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addComponent(btnAltCondicao, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jRadioButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioButton2)))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(edtValorFrete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(edtValorSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel26))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jFormattedTextField4))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtTotalDescontos, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(edtTotalAcrescimos))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(edtCustoTotal)
                                .addGap(5, 5, 5))))
                    .addComponent(jLabel21)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 922, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 861, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(edtModeloNota, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                            .addComponent(edtNumeroSerie)
                            .addComponent(edtNumeroNota)
                            .addComponent(edtFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                            .addComponent(edtCodFornecedor)))
                    .addComponent(btnAlterarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(edtDtEmissão, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(edtDtChegada, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(jLabel9))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(jLabel11)
                                .addComponent(jLabel15)
                                .addComponent(jLabel13)
                                .addComponent(jLabel14)
                                .addComponent(jLabel16)))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtValorItem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtQuantItem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtDescItem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtAcrescUn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtCustoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtCodProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                            .addComponent(edtUnMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRemoverItem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPesquisarItem, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAlterarItem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(jLabel26)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtValorSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtValorFrete, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel18)
                                .addComponent(jLabel19)
                                .addComponent(jLabel17))
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(edtCondicaoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(edtCodCondicaoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(edtTotalDescontos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(edtCustoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(edtTotalAcrescimos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(btnAltCondicao, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDescricaoForm1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane3.setViewportView(jPanel1);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Campos obrigatorios são marcados com ' * '");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDescricaoForm, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(42, 42, 42)
                                .addComponent(edtFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelar))
                            .addComponent(jLabel22)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1016, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDescricaoForm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    public void bloqueiaEDT() {
        this.edtAcrescUn.setEditable(false);
        this.edtCondicaoPagamento.setEditable(false);
        this.edtDescItem.setEditable(false);
        this.edtNome.setEditable(false);
        this.edtFuncionario.setEditable(false);
        this.edtDtChegada.setEnabled(false);
        this.edtNumeroNota.setEnabled(false);
        this.edtCustoProduto.setEditable(false);
        this.edtModeloNota.setEditable(false);
        this.edtAcrescUn.setEditable(false);
    }

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private boolean carregaCompra() {
        this.compra.setItensProdutos(itens);
        if (this.edtNumeroSerie.getValue() == null) {
            JOptionPane.showMessageDialog(this, "Numero da nota é obrigatório");
            this.edtNumeroNota.requestFocus();
            return false;
        }
        if (edtNumeroSerie.getValue()== null) {
            JOptionPane.showMessageDialog(this, "Numero de série nota é obrigatório");
            this.edtNumeroSerie.requestFocus();
            return false;
        }
        if (edtModeloNota.getText() == null) {
            JOptionPane.showMessageDialog(this, "Modelo da nota é obrigatório");
            this.edtModeloNota.requestFocus();
            return false;
        }

        if (compra.getItensProdutos().isEmpty()) {
            JOptionPane.showMessageDialog(this, "A compra deve possuir ao menos 1 item");
            this.edtCodProduto.requestFocus();
            return false;
        }
        if (compra.getCondicaoPagamento() == null) {
            JOptionPane.showMessageDialog(this, "Condição de pagamento é obrigatório");
            this.edtCodCondicaoPagamento.requestFocus();
            return false;
        }
        if (compra.getConstasPagar().isEmpty()) {
            JOptionPane.showMessageDialog(this, "A compra não possui nenhuma conta a pagar");
            this.edtCodCondicaoPagamento.requestFocus();
            return false;
        }
        if (edtDtEmissão.getDate() == null) {
            JOptionPane.showMessageDialog(this, "A compra não possui data de emissão");
            this.edtDtEmissão.requestFocus();
            return false;
        }
        if (edtDtChegada.getDate() == null) {
            JOptionPane.showMessageDialog(this, "A compra não possui data de chegada");
            this.edtDtChegada.requestFocus();
            return false;
        }

        if (contas.isEmpty()){
            JOptionPane.showMessageDialog(this, "A compra não possui contas a pagar");
            this.edtCodCondicaoPagamento.requestFocus();
            return false;
        }

        this.compra.setConstasPagar(contas);
        this.compra.setModeloNota(edtModeloNota.getText());
        this.compra.setNumeroNota(Integer.parseInt(edtNumeroNota.getValue().toString()));
        this.compra.setNumSerieNota(Integer.parseInt(edtNumeroSerie.getValue().toString()));
        this.compra.setDtEmisssao(edtDtEmissão.getDate());
        this.compra.setDtChegada(edtDtChegada.getDate());
        return true;
    }

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (!this.carregaCompra())
            return;

        try {
            new CompraService().save(compra);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Falha ao salvar dados: \n" + ex.getMessage());
            return;
        }

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void edtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtNomeActionPerformed

    private void edtFornecedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtFornecedorKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtFornecedorKeyPressed

    private void btnPesquisarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarItemActionPerformed
        PesquisarProduto.Callback callback = (p) -> {
            if (p == null) {
                if (itemProdutoSelecionado != null) {
                    edtCodProduto.setText(this.itemProdutoSelecionado.getId().toString());
                }
                return;
            } else {
                Optional<ItemProduto> item = itens.stream().filter(itemProduto -> itemProduto.getId().equals(p.getId())).findAny();
                if (item.isPresent()) {
                    if (JOptionPane.showConfirmDialog(this, "Item selecionado já existe na venda, deseja edita-lo ?",
                            "Atenção", JOptionPane.YES_NO_OPTION) == 1) {
                        return;
                    } else {
                        itemProdutoSelecionado = item.get();
                    }
                } else {
                    this.itemProdutoSelecionado = new ItemProduto();
                    this.itemProdutoSelecionado.buildItem(p);
                }
            }
            this.edtNome.setText(p.getNome());
            this.edtValorItem.setValue(p.getPrecoCompra());
            this.edtCustoProduto.setValue(p.getPrecoCompra());
            this.edtUnMedida.setText(p.getUnidadeMedida());
            this.edtCodProduto.setText(p.getId().toString());
            this.edtValorItem.setValue(p.getPrecoCompra());
            this.edtQuantItem.setValue(1D);
            this.itens.add(itemProdutoSelecionado);
        };
        new PesquisarProduto(this, true, callback).show();
    }//GEN-LAST:event_btnPesquisarItemActionPerformed

    private void btnRemoverItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverItemActionPerformed
        if (tblItens.getSelectedRow() < 0) {
            JOptionPane.showConfirmDialog(this, "Selecione um item para editar");
            return;
        }
        this.itens.remove(tblItens.getSelectedRow());
        tableModelProduto.setList(itens.toArray());
    }//GEN-LAST:event_btnRemoverItemActionPerformed

    private void btnAlterarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarItemActionPerformed
        if (tblItens.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "Selecione um item para editar");
            return;
        }
        this.itemProdutoSelecionado = itens.get(tblItens.getSelectedRow());
        this.edtNome.setText(itemProdutoSelecionado.getNome());
        this.edtValorItem.setValue(itemProdutoSelecionado.getPrecoCompra());
        this.edtCustoProduto.setValue(itemProdutoSelecionado.getValor());
        this.edtUnMedida.setText(itemProdutoSelecionado.getUnidadeMedida());
        this.edtCodProduto.setText(itemProdutoSelecionado.getId().toString());
        this.itens.add(itemProdutoSelecionado);
    }//GEN-LAST:event_btnAlterarItemActionPerformed

    private void btnAlterarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarFornecedorActionPerformed
        PesquisarFornecedor.Callback callback = (p) -> {
            if (p == null) {
                return;
            }
            this.compra.setFornecedor((Fornecedor) p);
            this.edtFornecedor.setText( p.getNome());
            this.edtCodFornecedor.setText(p.getId().toString());
        };
        new PesquisarFornecedor(this, true, callback).show();
    }//GEN-LAST:event_btnAlterarFornecedorActionPerformed

    private void btnAltCondicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltCondicaoActionPerformed
        PesquisarCondicaoPagamento.Callback callback = (condicao -> {
            if (condicao == null) {
                return;
            }
            this.compra.setCondicaoPagamento(condicao);
            edtCondicaoPagamento.setText(condicao.getNome());
            edtCodCondicaoPagamento.setValue(condicao.getId());
            this.buildParcelas();
        });
        new PesquisarCondicaoPagamento(this, true, callback).show();

    }//GEN-LAST:event_btnAltCondicaoActionPerformed

    public void buildParcelas() {
        List<Parcela> parcelas = compra.getCondicaoPagamento().getParcelas();
        Double valorTotal = (Double) edtCustoTotal.getValue();
        Integer qtd = parcelas.size();
        Double valor = valorTotal / qtd;

        parcelas.stream().forEach(parcela -> {
            ContaPagar conta = new ContaPagar();
            conta.setDataLancamento(new Date());
            Calendar data = new GregorianCalendar();
            data.setTime(new Date());
            data.add(Calendar.DATE, parcela.getDias());
            conta.setDataVencimento(data.getTime());
            conta.setParcela(parcela);
            conta.setValor(valor -
                    (compra.getCondicaoPagamento().getDesconto() * valor / 100) +
                    (compra.getCondicaoPagamento().getMulta() * valor / 100) +
                    (compra.getCondicaoPagamento().getJuros() * valor / 100)
            );
            contas.add(conta);
        });
        this.tableModelContas.setList(contas.toArray());
        this.tblContasApagar.setModel(tableModelContas);
    }

    private void edtFornecedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtFornecedorFocusLost
        edtFornecedor.setText(compra.getFornecedor().getId() + " " + compra.getFornecedor().getNome());
    }//GEN-LAST:event_edtFornecedorFocusLost

    private void btnAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemActionPerformed
        if (itemProdutoSelecionado == null) {
            JOptionPane.showMessageDialog(this, "Nenhum produto foi selecionado");
            return;
        }
        if ((Double) edtQuantItem.getValue() < 1D) {
            JOptionPane.showMessageDialog(this, " A quantidade do produto deve ser no minimo 1");
            this.edtQuantItem.requestFocus();
            return;
        }
        Optional<ItemProduto> itemOptional = itens.stream().filter(item -> item.getId().equals(itemProdutoSelecionado.getId())).findAny();
        if (itemOptional.isPresent()) {
            itens.remove(itemOptional.get());
        }

        itemProdutoSelecionado.setQuantidade((Double) edtQuantItem.getValue());
        itemProdutoSelecionado.setDescontoUnitario((Double) edtDescItem.getValue());
        itemProdutoSelecionado.setAcrescimoUnitario((Double) edtAcrescUn.getValue());

        if (!itens.contains(itemProdutoSelecionado))
            this.itens.add(itemProdutoSelecionado);

        tableModelProduto.setList(itens.toArray());
        tblItens.setModel(tableModelProduto);

        this.edtTotalDescontos.setValue(getTotalDescontos());
        this.edtTotalAcrescimos.setValue(getTotalAcresimos());
        this.edtCustoTotal.setValue(getTotalCompra());

    }//GEN-LAST:event_btnAddItemActionPerformed

    private void edtAcrescUnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtAcrescUnFocusLost
        //  itemProdutoSelecionado.setAcrescimoUnitario(edt);
    }//GEN-LAST:event_edtAcrescUnFocusLost

    private void edtCodFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtCodFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtCodFornecedorActionPerformed

    private void edtCodProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtCodProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtCodProdutoActionPerformed

    private void edtUnMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtUnMedidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtUnMedidaActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void edtValorItemPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_edtValorItemPropertyChange
        Double qtd = (Double) edtQuantItem.getValue();
        Double valorItem =(Double) edtValorItem.getValue();
        Double descUn = (Double) edtDescItem.getValue();
        Double acresUn =(Double) edtAcrescUn.getValue();
        edtCustoProduto.setValue((valorItem * qtd) - (descUn * qtd) + (acresUn * qtd));
    }//GEN-LAST:event_edtValorItemPropertyChange

    private void edtQuantItemPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_edtQuantItemPropertyChange
        Double qtd = (Double) edtQuantItem.getValue();
        Double valorItem =(Double) edtValorItem.getValue();
        Double descUn = (Double) edtDescItem.getValue();
        Double acresUn =(Double) edtAcrescUn.getValue();
        edtCustoProduto.setValue((valorItem * qtd) - (descUn * qtd) + (acresUn * qtd));
    }//GEN-LAST:event_edtQuantItemPropertyChange


    public ItemProduto getItemProdutoSelecionado() {
        return itemProdutoSelecionado;
    }

    public void setItemProdutoSelecionado(ItemProduto itemProdutoSelecionado) {
        this.itemProdutoSelecionado = itemProdutoSelecionado;
    }

    public List<ItemProduto> getItens() {
        return itens;
    }

    public void setItens(List<ItemProduto> itens) {
        this.itens = itens;
    }

    public Double getTotalDescontos() {
        return itens.stream().mapToDouble(value -> value.getTotaisDescontos()).sum();
    }

    public Double getTotalAcresimos() {
        return itens.stream().mapToDouble(value -> value.getTotaisAcrescimos()).sum();
    }

    public Double getTotalCompra() {
        return itens.stream().mapToDouble(ItemProduto::getPrecoCompra).sum();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCompraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCompraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCompraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCompraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastroCompraForm dialog = new CadastroCompraForm(new javax.swing.JFrame(), true, new Compra());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnAltCondicao;
    private javax.swing.JButton btnAlterarFornecedor;
    private javax.swing.JButton btnAlterarItem;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnPesquisarItem;
    private javax.swing.JButton btnRemoverItem;
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JFormattedTextField edtAcrescUn;
    private javax.swing.JFormattedTextField edtCodCondicaoPagamento;
    private javax.swing.JFormattedTextField edtCodFornecedor;
    private javax.swing.JFormattedTextField edtCodProduto;
    private javax.swing.JTextField edtCondicaoPagamento;
    private javax.swing.JFormattedTextField edtCustoProduto;
    private javax.swing.JFormattedTextField edtCustoTotal;
    private javax.swing.JFormattedTextField edtDescItem;
    private com.toedter.calendar.JDateChooser edtDtChegada;
    private com.toedter.calendar.JDateChooser edtDtEmissão;
    private javax.swing.JTextField edtFornecedor;
    private javax.swing.JTextField edtFuncionario;
    private javax.swing.JFormattedTextField edtModeloNota;
    private javax.swing.JTextField edtNome;
    private javax.swing.JFormattedTextField edtNumeroNota;
    private javax.swing.JFormattedTextField edtNumeroSerie;
    private javax.swing.JFormattedTextField edtQuantItem;
    private javax.swing.JFormattedTextField edtTotalAcrescimos;
    private javax.swing.JFormattedTextField edtTotalDescontos;
    private javax.swing.JTextField edtUnMedida;
    private javax.swing.JFormattedTextField edtValorFrete;
    private javax.swing.JFormattedTextField edtValorItem;
    private javax.swing.JFormattedTextField edtValorSeguro;
    private javax.swing.JFormattedTextField jFormattedTextField4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblDescricaoForm;
    private javax.swing.JLabel lblDescricaoForm1;
    private javax.swing.JTable tblContasApagar;
    private javax.swing.JTable tblItens;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
