/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.sistema;

import gui.swing.DialogPadrao;
import lib.model.interno.*;
import lib.service.GrupoFuncionarioService;
import lib.service.GrupoService;


import javax.swing.*;
import java.awt.*;
import java.sql.SQLException;
import java.util.*;
import java.util.stream.Collectors;

/**
 * @author diego.lenz
 */
public class CadastroGrupoOperadores extends DialogPadrao {
    private GrupoFuncionario grupoOperador;
    private Map<CategoriaModuloSistema, GrupoPermissaoPanel> gruposModulo;


    public CadastroGrupoOperadores(Window parent, boolean modal, GrupoFuncionario tipooperador) {
        super(parent, modal, ModuloSistema.SISTEMA_OPERADORES, NivelAcessoModulo.LEITURA_GRAVACAO);
        initComponents();
        this.grupoOperador = tipooperador;
        this.gruposModulo = new HashMap<>();
        setTitle(grupoOperador.getId() == null ? "Novo grupo de operadores" : "Editar grupo de operadores");
        lblTitulo.setText(getTitle());
        if (grupoOperador.getId() == null) {
            rdAtivo.setEnabled(false);
            rdinativo.setEnabled(false);
        }
        this.initPermissoes();
    }

    public void carregaedt() {
        edtNome.setText(grupoOperador.getNome());
        if (grupoOperador.getAtivo()){
            rdAtivo.setSelected(true);
        } else {
            rdinativo.setSelected(true);
        }

    }

    public void bloqueiaedt() {
        edtNome.setEditable(false);
        btnSalvar.setEnabled(false);
        pnlPermissoes.setEnabled(false);
        this.jPanel1.setEnabled(false);
        this.btnCancelar.setVisible(false);
        this.btnSalvar.setVisible(false);
    }

    public void desbloqueiaedt() {
        edtNome.setEditable(true);
        btnSalvar.setEnabled(true);
    }

    private void initPermissoes() {
        Arrays.stream(CategoriaModuloSistema.values())
                .sorted(Comparator.comparing(CategoriaModuloSistema::getDescricao))
                .forEach(categoria -> {
                    GrupoPermissaoPanel panel = new GrupoPermissaoPanel(categoria,
                            grupoOperador.getPermissoes().stream().filter(permissaoAcesso -> permissaoAcesso.getModulo().getCategoria().equals(categoria)).collect(Collectors.toList()));
                    gruposModulo.put(categoria, panel);
                    pnlPermissoes.add(panel);
                });
        pnlPermissoes.revalidate();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblTitulo = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pnlPermissoes = new javax.swing.JPanel();
        edtNome = new javax.swing.JTextField();
        lblTitulo1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        rdAtivo = new javax.swing.JRadioButton();
        rdinativo = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de grupo de funcionarios");
        setResizable(false);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/group_pepple.png"))); // NOI18N
        lblTitulo.setText("Novo grupo de operadores");

        btnSalvar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        pnlPermissoes.setBackground(new java.awt.Color(255, 255, 255));
        pnlPermissoes.setLayout(new javax.swing.BoxLayout(pnlPermissoes, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane2.setViewportView(pnlPermissoes);

        lblTitulo1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTitulo1.setText("Permissoes");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nome do grupo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(edtNome)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lblTitulo1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(lblTitulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        buttonGroup1.add(rdAtivo);
        rdAtivo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdAtivo.setSelected(true);
        rdAtivo.setText("Ativo");

        buttonGroup1.add(rdinativo);
        rdinativo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdinativo.setText("Inativo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelar))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(rdAtivo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdinativo))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 545, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTitulo)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rdAtivo)
                        .addComponent(rdinativo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnSalvar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        grupoOperador.setNome(edtNome.getText());
        if (grupoOperador.getNome() == null || grupoOperador.getNome().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nome invalido, adicione um nome ao grupo e tente novamente");
            edtNome.requestFocus();
            return;
        }
        gruposModulo.values().stream().forEach(grupoPermissaoPanel -> {
            grupoOperador.getPermissoes().addAll(grupoPermissaoPanel.buildPermissoes());
        });
        try {
            new GrupoFuncionarioService().save(grupoOperador);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Falha ao salvar, os seguintes exeções foram encontradas \n" + ex.getMessage());
            try {
                new GrupoFuncionarioService().rollback();
            } catch (SQLException exe) {
                System.out.println(exe);
            }
            return;
        }
        JOptionPane.showMessageDialog(this, "Salvo com sucesso");
        dispose();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {
        boolean cancelar;
        if (JOptionPane.showConfirmDialog(this, "Tem certeza de que deseja cancelar?", "Cancelar",
                JOptionPane.YES_NO_OPTION) == 0)
            cancelar = true;
        else cancelar = false;

        if (cancelar) {
            this.dispose();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField edtNome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JPanel pnlPermissoes;
    private javax.swing.JRadioButton rdAtivo;
    private javax.swing.JRadioButton rdinativo;
    // End of variables declaration//GEN-END:variables
}
