/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.servicos;

import gui.modeltable.TableModelServico;
import gui.servicos.CadastroServicoForm;
import gui.swing.SociusTab;
import gui.swing.WindowPadrao;
import jdk.nashorn.internal.scripts.JO;
import lib.dao.imp.servico.ServicoDao;
import lib.model.interno.ModuloSistema;
import lib.model.servico.Servico;
import lib.service.ServicoService;

import javax.swing.*;
import java.awt.*;
import java.util.List;

/**
 *
 * @author Diego
 */
public class ConsultaServicos extends SociusTab implements WindowPadrao {
    private List<Servico> servicos;
    private TableModelServico tableModelServico;
    private Servico servico;
    private CadastroServicoForm cadastroServicoForm;
    private ServicoService servicoService;

    /**
     * Creates new form ConsultaPanel
     */
    public ConsultaServicos(Window parent) {
        super(parent, ModuloSistema.PRODUTOS_SERVICOS);
        initComponents();
        tableModelServico=new TableModelServico();
        servicoService = new ServicoService();
        btnPesquisarActionPerformed(null);
        initTable();
    }
    public void initTable(){
        this.jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
        this.jTable1.getColumnModel().getColumn(1).setPreferredWidth(200);
        this.jTable1.getColumnModel().getColumn(2).setPreferredWidth(100);
        this.jTable1.getColumnModel().getColumn(3).setPreferredWidth(50);
        this.jTable1.getColumnModel().getColumn(4).setPreferredWidth(50);
        this.jTable1.getColumnModel().getColumn(5).setPreferredWidth(50);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnPesquisar = new javax.swing.JButton();
        edtPesquisa = new javax.swing.JTextField();
        btnDesativar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnVisualizar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setName("Consulta"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnPesquisar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnDesativar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDesativar.setText("Excluir");
        btnDesativar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesativarActionPerformed(evt);
            }
        });

        btnAlterar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAlterar.setText("Editar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnNovo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnVisualizar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnVisualizar.setText("Visualizar");
        btnVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(edtPesquisa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPesquisar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVisualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDesativar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPesquisar)
                    .addComponent(edtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDesativar)
                    .addComponent(btnAlterar)
                    .addComponent(btnNovo)
                    .addComponent(btnVisualizar))
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents


    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            servicos=new ServicoDao().getAllAtivos(edtPesquisa.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

        tableModelServico.setList(servicos.toArray());
        jTable1.setModel(tableModelServico);
        if (servicos.isEmpty()){
            if (evt != null)
                JOptionPane.showMessageDialog(this, "Nenhum resultado encontrado");
        } else
            jTable1.setRowSelectionInterval(0,0);
    }

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {
        cadastroServicoForm=new CadastroServicoForm(getWindowParent(), true, new Servico());
        cadastroServicoForm.show();
    }

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {
        if (jTable1.getSelectedRow()<0){
            JOptionPane.showMessageDialog(this,"Selecione um Serviço para alterar!");
            return;
        }
        servico=servicos.get(jTable1.getSelectedRow());
        cadastroServicoForm=new CadastroServicoForm(getWindowParent(), true, servico);
        cadastroServicoForm.carregaEdt();
        cadastroServicoForm.show();
    }

    private void btnVisualizarActionPerformed(java.awt.event.ActionEvent evt) {
        if (jTable1.getSelectedRow()<0){
            JOptionPane.showMessageDialog(this,"Selecione um Serviço para alterar!");
            return;
        }
        servico=servicos.get(jTable1.getSelectedRow());
        cadastroServicoForm=new CadastroServicoForm(getWindowParent(), true, servico);
        cadastroServicoForm.carregaEdt();
        cadastroServicoForm.bloqueiaEdt();
        cadastroServicoForm.show();
    }

    private void btnDesativarActionPerformed(java.awt.event.ActionEvent evt) {                                             
        if (jTable1.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "Selecione um registro para continuar");
            return;
        }
        Servico produtoselecionado = servicos.get(jTable1.getSelectedRow());
        try {
            servicoService.deleteByID(produtoselecionado.getId());
            JOptionPane.showMessageDialog(this, "Excluido com sucesso");
            return;
        } catch (Exception e) {
            if (JOptionPane.showConfirmDialog(this,"Não é possivel excluir o registro, deseja desativa-lo?", "ATENÇÂO", JOptionPane.YES_NO_OPTION)==0) {
                if (!produtoselecionado.isAtivo())
                    JOptionPane.showMessageDialog(this, "Serviço já está desativada");
                try {
                    servicoService.update(produtoselecionado);
                    JOptionPane.showMessageDialog(this,
                            "Desativado com sucesso"
                    );
                    return;
                } catch (Exception e1) {
                    JOptionPane.showMessageDialog(this, "Não foi possivel desativar");
                }
            }
        }
        tableModelServico.setList(servicos.toArray());
                                
    }                                            


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnDesativar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnVisualizar;
    private javax.swing.JTextField edtPesquisa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
