/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.comercial.venda;

import gui.financeiro.CondicaoPagamento.PesquisarCondicaoPagamento;
import gui.modeltable.TableModelContas;
import gui.modeltable.TableModelContasReceber;
import gui.modeltable.TableModelItemProduto;
import gui.modeltable.TableModelServico;
import gui.pessoas.clientes.PesquisarCliente;
import gui.produtos.PesquisarProduto;
import gui.swing.DialogPadrao;
import gui.swing.SwingFormatterFactory;
import javafx.scene.input.KeyCode;
import lib.model.comercial.ItemProduto;
import lib.model.comercial.VendaProduto;
import lib.model.comercial.frete.TipoFrete;
import lib.model.financeiro.CondicaoPagamento.CondicaoPagamento;
import lib.model.financeiro.contas.ContaReceber;
import lib.model.financeiro.parcela.Parcela;
import lib.model.interno.ModuloSistema;
import lib.model.interno.NivelAcessoModulo;
import lib.model.pessoa.cliente.Cliente;
import lib.model.produto.Produto;
import lib.model.servico.ItemServico;
import lib.service.*;
import util.Util;

import javax.swing.*;
import java.awt.*;
import java.sql.SQLException;
import java.util.List;
import java.util.*;

/**
 * @author Diego
 */

public class CadastroVendaProdutoForm extends DialogPadrao {

    private VendaProduto venda;
    private ItemProduto itemProdutoSelecionado;
    private ItemServico itemServicoSelecionado;
    private TableModelItemProduto tableModelProduto;
    private TableModelServico tableModelServico;
    private TableModelContasReceber tableModelContas;
    private List<ContaReceber> contas;
    private Boolean camposBloquados;

    /**
     * Creates new form CadastroVendaForm
     */
    public CadastroVendaProdutoForm(Window parent, boolean modal, VendaProduto venda) {
        super(parent, modal, ModuloSistema.COMPRAS, NivelAcessoModulo.LEITURA_GRAVACAO);
        camposBloquados = true;
        initComponents();
        this.venda = venda;
        tableModelProduto = new TableModelItemProduto();
        tableModelContas = new TableModelContasReceber();
        tableModelServico = new TableModelServico();
        contas = new ArrayList<>();
        if (venda.getModeloNota() == null) {
            lblStatus.setVisible(false);
            camposBloquados = true;
            bloqueia();
        }
        this.bloqueia();
        this.initDados();
    }

    public void carregar() {
        if (!venda.isAtivo()) {
            lblStatus.setText("Cancelada");
            lblStatus.setForeground(Color.RED);
        }
        edtCliente.setText(venda.getCliente().getNome());
        edtCodCliente.setText(venda.getCliente().getId().toString());
        edtNumeroSerie.setText(venda.getNumSerieNota().toString());
        edtNumeroNota.setText(venda.getNumeroNota().toString());
        edtModeloNota.setText(venda.getModeloNota());
        edtDtEmissão.setDate(venda.getDtEmisssao());
        edtDtChegada.setDate(venda.getDtChegada());
        tableModelProduto.setList(venda.getItensProdutos().toArray());
        edtValorSeguro.setValue(venda.getValorSeguro());
        edtValorFrete.setValue(venda.getValorFrete());
        edtCustoTotal.setValue(venda.getTotalVenda());
        edtOutrasDespesas.setValue(venda.getOutrasDespesas());
        edtCodCondicaoPagamento.setText(venda.getCondicaoPagamento().getId().toString());
        edtCondicaoPagamento.setText(venda.getCondicaoPagamento().getNome());
        tableModelContas.setList(venda.getContas().toArray());
        tblContasApagar.setModel(tableModelContas);
        tableModelProduto.setList(venda.getItensProdutos().toArray());
        tblItens.setModel(tableModelProduto);
        if (venda.getTipoFrete().equals(TipoFrete.CIF))
            rdTipoFreteCIF.setSelected(true);
        else
            rdFreteFOB.setSelected(true);
        lblDescricaoForm.setText("Visualizar venda");
    }

    public void initDados() {
        this.edtDtChegada.setDate(new Date());
        this.edtDtEmissão.setDate(new Date());
        if (venda.getTipoFrete() == null)
            this.rdTipoFreteCIF.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        edtFuncionario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lblDescricaoForm = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        edtDtChegada = new com.toedter.calendar.JDateChooser();
        edtDtEmissão = new com.toedter.calendar.JDateChooser();
        edtModeloNota = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItens = new javax.swing.JTable();
        btnAlterarFornecedor = new javax.swing.JButton();
        btnAlterarFornecedor.setContentAreaFilled(false);
        btnAlterarFornecedor.setOpaque(true);
        btnAlterarFornecedor.setBackground(Color.white);
        edtCliente = new javax.swing.JTextField();
        btnRemoverItem = new javax.swing.JButton();
        btnRemoverItem.setContentAreaFilled(false);   btnRemoverItem.setOpaque(true);   btnRemoverItem.setBackground(Color.white);
        btnAlterarItem = new javax.swing.JButton();
        btnAlterarItem.setContentAreaFilled(false);   btnAlterarItem.setOpaque(true);   btnAlterarItem.setBackground(Color.white);
        edtNumeroNota = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        edtNumeroSerie = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        edtCodCliente = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblContasApagar = new javax.swing.JTable();
        lblDescricaoForm1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        edtCondicaoPagamento = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnAltCondicao = new javax.swing.JButton();
        btnAltCondicao.setContentAreaFilled(false);
        btnAltCondicao.setOpaque(true);
        btnAltCondicao.setBackground(Color.white);
        jLabel20 = new javax.swing.JLabel();
        edtCodProduto = new javax.swing.JFormattedTextField();
        edtNome = new javax.swing.JTextField();
        btnPesquisarItem = new javax.swing.JButton();
        btnPesquisarItem.setContentAreaFilled(false);
        btnPesquisarItem.setOpaque(true);
        btnPesquisarItem.setBackground(Color.white);
        edtUnMedida = new javax.swing.JTextField();
        edtQuantItem = new javax.swing.JFormattedTextField();
        edtValorItem = new javax.swing.JFormattedTextField();
        edtDescItem = new javax.swing.JFormattedTextField();
        edtAcrescUn = new javax.swing.JFormattedTextField();
        edtCustoProduto = new javax.swing.JFormattedTextField();
        btnAddItem = new javax.swing.JButton();
        btnAddItem.setContentAreaFilled(false);   btnAddItem.setOpaque(true);   btnAddItem.setBackground(Color.white);
        lblCodProd = new javax.swing.JLabel();
        lblProd = new javax.swing.JLabel();
        lblUn = new javax.swing.JLabel();
        lblqtd = new javax.swing.JLabel();
        lblCusto = new javax.swing.JLabel();
        lblDescUn = new javax.swing.JLabel();
        lblAcrescUn = new javax.swing.JLabel();
        lblCustoProd = new javax.swing.JLabel();
        edtTotalDescontos = new javax.swing.JFormattedTextField();
        edtTotalAcrescimos = new javax.swing.JFormattedTextField();
        edtCustoTotal = new javax.swing.JFormattedTextField();
        edtCodCondicaoPagamento = new javax.swing.JFormattedTextField();
        edtOutrasDespesas = new javax.swing.JFormattedTextField();
        lblOutrasDespesas = new javax.swing.JLabel();
        edtValorSeguro = new javax.swing.JFormattedTextField();
        lblSeguro = new javax.swing.JLabel();
        edtValorFrete = new javax.swing.JFormattedTextField();
        lblValorFrete = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        rdTipoFreteCIF = new javax.swing.JRadioButton();
        jLabel23 = new javax.swing.JLabel();
        rdFreteFOB = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de venda");
        setResizable(false);

        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSalvar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        edtFuncionario.setEditable(false);
        edtFuncionario.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Funcionario");

        lblDescricaoForm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDescricaoForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shoppingcart_to_compra_12829 (1).png"))); // NOI18N
        lblDescricaoForm.setText("Nova venda");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        edtDtChegada.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        edtDtEmissão.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        edtModeloNota.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edtModeloNota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                validaNota(evt);
            }
        });

        tblItens.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblItens.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tblItens);
        if (tblItens.getColumnModel().getColumnCount() > 0) {
            tblItens.getColumnModel().getColumn(0).setPreferredWidth(5);
            tblItens.getColumnModel().getColumn(1).setPreferredWidth(25);
            tblItens.getColumnModel().getColumn(2).setPreferredWidth(10);
            tblItens.getColumnModel().getColumn(3).setPreferredWidth(10);
            tblItens.getColumnModel().getColumn(4).setPreferredWidth(10);
            tblItens.getColumnModel().getColumn(5).setPreferredWidth(10);
        }

        btnAlterarFornecedor.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnAlterarFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pesquisar.png"))); // NOI18N
        btnAlterarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarFornecedorActionPerformed(evt);
            }
        });

        edtCliente.setEditable(false);
        edtCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnRemoverItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/erro_icon.png"))); // NOI18N
        btnRemoverItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverItemActionPerformed(evt);
            }
        });

        btnAlterarItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit_modify_icon-icons.com_72390.png"))); // NOI18N
        btnAlterarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarItemActionPerformed(evt);
            }
        });

        edtNumeroNota.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        edtNumeroNota.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edtNumeroNota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                validaNota(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Serie da nota *");

        edtNumeroSerie.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        edtNumeroSerie.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edtNumeroSerie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                validaNota(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nm da nota *");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Modelo da nota *");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Data de emissão *");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Data de chegada *");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Código *");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Cliente *");

        edtCodCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        edtCodCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edtCodCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtCodClienteKeyPressed(evt);
            }
        });

        tblContasApagar.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tblContasApagar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblContasApagar.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(tblContasApagar);

        lblDescricaoForm1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDescricaoForm1.setText("Parcelas");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Condição de pagamento *");

        edtCondicaoPagamento.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Total de descontos");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("total do acresimo");

        btnAltCondicao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pesquisar.png"))); // NOI18N
        btnAltCondicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltCondicaoActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Valor Total");

        edtCodProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edtCodProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtCodProdutoKeyPressed(evt);
            }
        });

        edtNome.setEditable(false);
        edtNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${itemProdutoSelecionado.nome}"), edtNome, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        btnPesquisarItem.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnPesquisarItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pesquisar.png"))); // NOI18N
        btnPesquisarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarItemActionPerformed(evt);
            }
        });

        edtUnMedida.setEditable(false);
        edtUnMedida.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        edtQuantItem.setFormatterFactory(  SwingFormatterFactory.buildNumeroReal(0D, null));
        edtQuantItem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edtQuantItem.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                calculaValorTotalPorItem(evt);
            }
        });

        edtValorItem.setFormatterFactory(  SwingFormatterFactory.buildMoeda(0D, null));
        edtValorItem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${itemProdutoSelecionado.valor}"), edtValorItem, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        edtValorItem.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                calculaValorTotalPorItem(evt);
            }
        });

        edtDescItem.setFormatterFactory(  SwingFormatterFactory.buildMoeda(0D, null));
        edtDescItem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${itemProdutoSelecionado.descontoUnitario}"), edtDescItem, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        edtDescItem.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                calculaValorTotalPorItem(evt);
            }
        });

        edtAcrescUn.setFormatterFactory(  SwingFormatterFactory.buildMoeda(0D, null));
        edtAcrescUn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${itemProdutoSelecionado.acrescimoUnitario}"), edtAcrescUn, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        edtAcrescUn.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                calculaValorTotalPorItem(evt);
            }
        });

        edtCustoProduto.setEditable(false);
        edtCustoProduto.setFormatterFactory(  SwingFormatterFactory.buildMoeda(0D, null));
        edtCustoProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${itemProdutoSelecionado.valorTotal}"), edtCustoProduto, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        btnAddItem.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnAddItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CertoIcon.png"))); // NOI18N
        btnAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemActionPerformed(evt);
            }
        });

        lblCodProd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCodProd.setText("Código");

        lblProd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblProd.setText("Produto");

        lblUn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblUn.setText("Und");

        lblqtd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblqtd.setText("Qtd");

        lblCusto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCusto.setText("Valor UN");

        lblDescUn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDescUn.setText("Desc UN");

        lblAcrescUn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAcrescUn.setText("Acresc. UN");

        lblCustoProd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCustoProd.setText("Custo");

        edtTotalDescontos.setEditable(false);
        edtTotalDescontos.setFormatterFactory(  SwingFormatterFactory.buildNumeroReal(0D, 1000000D)
        );
        edtTotalDescontos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        edtTotalAcrescimos.setEditable(false);
        edtTotalAcrescimos.setFormatterFactory(  SwingFormatterFactory.buildMoeda(0D, 100000000D)
        );
        edtTotalAcrescimos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        edtCustoTotal.setEditable(false);
        edtCustoTotal.setFormatterFactory(  SwingFormatterFactory.buildMoeda(0D, null));
        edtCustoTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        edtCodCondicaoPagamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtCodCondicaoPagamentoKeyPressed(evt);
            }
        });

        edtOutrasDespesas.setFormatterFactory(  SwingFormatterFactory.buildMoeda(0D, null));
        edtOutrasDespesas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edtOutrasDespesas.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                atualizaValoTotalVenda(evt);
            }
        });

        lblOutrasDespesas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblOutrasDespesas.setText("Outras despesas");

        edtValorSeguro.setFormatterFactory(  SwingFormatterFactory.buildMoeda(0D, null));
        edtValorSeguro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edtValorSeguro.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                atualizaValoTotalVenda(evt);
            }
        });

        lblSeguro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSeguro.setText("Valor seguro");

        edtValorFrete.setFormatterFactory(  SwingFormatterFactory.buildMoeda(0D, null));
        edtValorFrete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edtValorFrete.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                atualizaValoTotalVenda(evt);
            }
        });

        lblValorFrete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblValorFrete.setText("Valor frete");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        rdTipoFreteCIF.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdTipoFreteCIF);
        rdTipoFreteCIF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdTipoFreteCIF.setText("CIF");
        rdTipoFreteCIF.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdTipoFreteCIFItemStateChanged(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("Tipo frete");

        rdFreteFOB.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdFreteFOB);
        rdFreteFOB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdFreteFOB.setText("FOB");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rdTipoFreteCIF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdFreteFOB))
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdTipoFreteCIF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdFreteFOB, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescricaoForm1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(edtNumeroNota, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(edtNumeroSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(edtModeloNota, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addComponent(edtCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(edtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(edtDtEmissão, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(edtDtChegada, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblCodProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(edtCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(edtNome)
                                        .addComponent(lblProd, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnPesquisarItem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(edtUnMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblUn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(edtQuantItem, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblqtd, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(edtValorItem, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(edtDescItem, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblDescUn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblAcrescUn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(edtAcrescUn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(14, 14, 14)
                                            .addComponent(lblCustoProd, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(edtCustoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblValorFrete)
                                                .addComponent(edtValorFrete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(edtValorSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblSeguro))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(lblOutrasDespesas)
                                                .addComponent(edtOutrasDespesas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel18)
                                                    .addGap(211, 211, 211))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(edtCodCondicaoPagamento)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(edtCondicaoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                            .addComponent(btnAltCondicao, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(edtTotalDescontos, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(edtTotalAcrescimos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(edtCustoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterarItem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemoverItem, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(edtModeloNota, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtNumeroSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtNumeroNota, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnAlterarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(edtDtEmissão, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtDtChegada, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblProd)
                                .addComponent(lblCodProd))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblDescUn)
                                .addComponent(lblCusto)
                                .addComponent(lblqtd)
                                .addComponent(lblAcrescUn)
                                .addComponent(lblCustoProd)
                                .addComponent(lblUn)))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtValorItem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtQuantItem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtDescItem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtAcrescUn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtCustoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtUnMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnRemoverItem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarItem, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterarItem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblSeguro)
                                .addComponent(lblOutrasDespesas))
                            .addComponent(lblValorFrete, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edtValorSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtValorFrete, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtOutrasDespesas, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edtCondicaoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtCodCondicaoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnAltCondicao, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jLabel17)
                            .addComponent(jLabel19))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edtCustoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtTotalAcrescimos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtTotalDescontos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDescricaoForm1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane3.setViewportView(jPanel1);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Campos obrigatorios são marcados com ' * '");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Status : ");

        lblStatus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblStatus.setText("Ativa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1054, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescricaoForm, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(42, 42, 42)
                                .addComponent(edtFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel22))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(513, 513, 513)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(516, 516, 516)
                                .addComponent(btnSalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelar)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescricaoForm)
                    .addComponent(jLabel9)
                    .addComponent(lblStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bloqueia() {
        camposBloquados = true;
        this.edtCondicaoPagamento.setEditable(false);
        this.edtFuncionario.setEditable(false);
        this.edtDtChegada.setEnabled(false);
        this.edtDtEmissão.setEnabled(false);
        this.edtValorFrete.setEditable(false);
        this.edtOutrasDespesas.setEditable(false);
        this.edtValorSeguro.setEditable(false);
        this.tblItens.setEnabled(false);
        this.tblContasApagar.setEnabled(false);
        //  this.edtCodCliente.setEnabled(false);
        this.edtCodCondicaoPagamento.setEnabled(false);
        this.rdTipoFreteCIF.setEnabled(false);
        this.rdFreteFOB.setEnabled(false);
        this.lblCodProd.setEnabled(false);
        this.lblAcrescUn.setEnabled(false);
        this.lblDescUn.setEnabled(false);
        this.lblUn.setEnabled(false);
        this.lblCustoProd.setEnabled(false);
        this.lblCusto.setEnabled(false);
        this.lblqtd.setEnabled(false);
        this.lblProd.setEnabled(false);
        this.edtCodProduto.setEnabled(false);
        this.edtQuantItem.setEnabled(false);
        this.edtDescItem.setEnabled(false);
        this.edtNome.setEnabled(false);
        this.edtCustoProduto.setEnabled(false);
        this.edtAcrescUn.setEnabled(false);
        this.edtUnMedida.setEnabled(false);
        this.edtAcrescUn.setEnabled(false);
        this.edtValorItem.setEnabled(false);
        btnAddItem.setEnabled(false);
        btnAltCondicao.setEnabled(false);
        //   btnAlterarFornecedor.setEnabled(false);
        btnRemoverItem.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnSalvar.setEnabled(false);
        btnPesquisarItem.setEnabled(false);
        btnAlterarItem.setEnabled(false);
    }

    private void desbloqueia() {
        camposBloquados = false;
        this.edtCondicaoPagamento.setEditable(true);
        this.edtFuncionario.setEditable(true);
        this.edtDtChegada.setEnabled(true);
        this.edtDtEmissão.setEnabled(true);
        this.edtValorFrete.setEditable(true);
        this.edtOutrasDespesas.setEditable(true);
        this.edtValorSeguro.setEditable(true);
        this.tblItens.setEnabled(true);
        this.tblContasApagar.setEnabled(true);
        this.edtCodCliente.setEnabled(true);
        this.edtCodCondicaoPagamento.setEnabled(true);
        this.rdTipoFreteCIF.setEnabled(true);
        this.rdFreteFOB.setEnabled(true);
        this.lblCodProd.setEnabled(true);
        this.lblAcrescUn.setEnabled(true);
        this.lblDescUn.setEnabled(true);
        this.lblUn.setEnabled(true);
        this.lblCustoProd.setEnabled(true);
        this.lblCusto.setEnabled(true);
        this.lblqtd.setEnabled(true);
        this.lblProd.setEnabled(true);
        this.edtCodProduto.setEnabled(true);
        this.edtQuantItem.setEnabled(true);
        this.edtDescItem.setEnabled(true);
        this.edtNome.setEnabled(true);
        this.edtCustoProduto.setEnabled(true);
        this.edtAcrescUn.setEnabled(true);
        this.edtUnMedida.setEnabled(true);
        this.edtAcrescUn.setEnabled(true);
        this.edtValorItem.setEnabled(true);
        btnAddItem.setEnabled(true);
        btnAltCondicao.setEnabled(true);
        btnAlterarFornecedor.setEnabled(true);
        btnRemoverItem.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnSalvar.setEnabled(true);
        btnPesquisarItem.setEnabled(true);
        btnAlterarItem.setEnabled(true);
    }

    public void bloqueiaEDT() {
        this.edtCondicaoPagamento.setEditable(false);
        this.edtFuncionario.setEditable(false);
        this.edtDtChegada.setEnabled(false);
        this.edtNumeroNota.setEnabled(false);
        this.edtDtEmissão.setEnabled(false);
        this.edtTotalAcrescimos.setEditable(false);
        this.edtTotalDescontos.setEditable(false);
        edtNumeroSerie.setEditable(false);
        this.edtValorFrete.setEditable(false);
        this.edtOutrasDespesas.setEditable(false);
        this.edtValorSeguro.setEditable(false);
        this.edtModeloNota.setEditable(false);
        this.tblItens.setEnabled(false);
        this.tblContasApagar.setEnabled(false);
        this.edtCodCliente.setEnabled(false);
        this.edtCodCondicaoPagamento.setEnabled(false);
        this.rdTipoFreteCIF.setEnabled(false);
        this.rdFreteFOB.setEnabled(false);
        this.lblCodProd.setVisible(false);
        this.lblAcrescUn.setVisible(false);
        this.lblDescUn.setVisible(false);
        this.lblUn.setVisible(false);
        this.lblCustoProd.setVisible(false);
        this.lblCusto.setVisible(false);
        this.lblqtd.setVisible(false);
        this.lblProd.setVisible(false);
        this.edtCodProduto.setVisible(false);
        this.edtQuantItem.setVisible(false);
        this.edtDescItem.setVisible(false);
        this.edtNome.setVisible(false);
        this.edtCustoProduto.setVisible(false);
        this.edtAcrescUn.setVisible(false);
        this.edtUnMedida.setVisible(false);
        this.edtAcrescUn.setVisible(false);
        this.edtValorItem.setVisible(false);
        btnAddItem.setVisible(false);
        btnAltCondicao.setVisible(false);
        btnAlterarFornecedor.setVisible(false);
        btnRemoverItem.setVisible(false);
        btnCancelar.setVisible(false);
        btnSalvar.setVisible(false);
        btnPesquisarItem.setVisible(false);
        btnAlterarItem.setVisible(false);
    }

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        if (btnCancelar.getText().equalsIgnoreCase("voltar"))
            dispose();
        if (JOptionPane.showInternalConfirmDialog(this, "Nenhum dado da venda será salvo, deseja realmente cancelar",
                "Atenção", JOptionPane.YES_NO_OPTION) == 0) {
            dispose();
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private boolean carregaValidaVenda() {
        if (this.edtNumeroSerie.getValue() == null) {
            JOptionPane.showMessageDialog(this, "Numero da nota é obrigatório");
            this.edtNumeroNota.requestFocus();
            return false;
        }
        if (edtNumeroSerie.getValue() == null) {
            JOptionPane.showMessageDialog(this, "Numero de série nota é obrigatório");
            this.edtNumeroSerie.requestFocus();
            return false;
        }
        if (edtModeloNota.getText() == null) {
            JOptionPane.showMessageDialog(this, "Modelo da nota é obrigatório");
            this.edtModeloNota.requestFocus();
            return false;
        }

        if (venda.getCliente() == null) {
            JOptionPane.showMessageDialog(this, "Cliente não informado");
            edtCodCliente.requestFocus();
            return false;
        }

        if (venda.getItensProdutos().isEmpty()) {
            JOptionPane.showMessageDialog(this, "A venda deve possuir ao menos 1 item");
            this.edtCodProduto.requestFocus();
            return false;
        }
        if (venda.getCondicaoPagamento() == null) {
            JOptionPane.showMessageDialog(this, "Condição de pagamento é obrigatório");
            this.edtCodCondicaoPagamento.requestFocus();
            return false;
        }
        if (edtDtEmissão.getDate() == null) {
            JOptionPane.showMessageDialog(this, "A venda não possui data de emissão");
            this.edtDtEmissão.requestFocus();
            return false;
        }
        if (edtDtChegada.getDate() == null) {
            JOptionPane.showMessageDialog(this, "A venda não possui data de chegada");
            this.edtDtChegada.requestFocus();
            return false;
        }
        if (edtDtEmissão.getDate().compareTo(new Date()) > 0) {
            JOptionPane.showMessageDialog(this, "A data de emissão deve ser igual ou menor que a data de hoje");
            this.edtDtChegada.requestFocus();
            return false;
        }
        if (edtDtEmissão.getDate().compareTo(edtDtChegada.getDate()) >= 0) {
            JOptionPane.showMessageDialog(this, "A data de chegada deve ser igual ou maior que a data de emissão");
            this.edtDtChegada.requestFocus();
            return false;
        }

        if (contas.isEmpty()) {
            JOptionPane.showMessageDialog(this, "A venda não possui contas a pagar");
            this.edtCodCondicaoPagamento.requestFocus();
            return false;
        }
        if (rdTipoFreteCIF.isSelected()) {
            this.venda.setTipoFrete(TipoFrete.CIF);
            this.venda.setValorFrete(0D);
            this.venda.setValorSeguro(0D);
            this.venda.setOutrasDespesas(0D);
            this.venda.getItensProdutos().stream().forEach(itemProduto -> itemProduto.setValorRateio(0D));
        } else {
            this.venda.setTipoFrete(TipoFrete.FOB);
            this.venda.setValorFrete((Double) edtValorFrete.getValue());
            this.venda.setValorSeguro((Double) edtValorSeguro.getValue());
            this.venda.setOutrasDespesas((Double) edtOutrasDespesas.getValue());
        }

        this.venda.setAtivo(true);
        this.venda.setContas(contas);
        this.venda.setModeloNota(edtModeloNota.getText());
        this.venda.setNumeroNota(Integer.parseInt(edtNumeroNota.getValue().toString()));
        this.venda.setNumSerieNota(Integer.parseInt(edtNumeroSerie.getValue().toString()));
        this.venda.setDtEmisssao(edtDtEmissão.getDate());
        this.venda.setDtChegada(edtDtChegada.getDate());
        this.buildItens();
        return true;
    }

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (!this.carregaValidaVenda()) {

            return;
        }
        try {
            VendaProdutoService vendaProdutoService = new VendaProdutoService();
            vendaProdutoService.setAutoCommit(false);
            vendaProdutoService.save(venda);
            ProdutoService produtoService = new ProdutoService();
            List<Produto> produtos = this.atualizaEstoque();
            for (Produto p : produtos){
                produtoService.update(p);
            }

            vendaProdutoService.commit();
            vendaProdutoService.setAutoCommit(true);

            JOptionPane.showMessageDialog(this, "Venda salva com sucesso");
            dispose();
        } catch (SQLException ex) {
            try {
                new Service().clear();
            } catch (SQLException e){
            }
            JOptionPane.showMessageDialog(this, "Falha ao salvar dados: \n" + ex.getMessage());
            return;
        }

    }//GEN-LAST:event_btnSalvarActionPerformed

    private List<Produto> atualizaEstoque() {
        List<Produto> produtos = new ArrayList<>();
        this.venda.getItensProdutos().stream().forEach(itemProduto -> {
            Produto p = new Produto();
            p = p.buildProduto(itemProduto);
            p.setValor(itemProduto.getValorUnitario() + itemProduto.getValorRateio() - itemProduto.getDescontoUnitario() + itemProduto.getAcrescimoUnitario());
            p.setQuantidadeEstoque(itemProduto.getQuantidadeEstoque() - itemProduto.getQuantidade());
            //p.setUltimoFornecedor(venda.getFornecedor());
            p.setDataUltimaVenda(new Date());
            produtos.add(p);
        });
        return produtos;
    }

    private void btnPesquisarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarItemActionPerformed
        PesquisarProduto.Callback callback = (p) -> {
            if (p == null) {
                if (itemProdutoSelecionado != null) {
                    edtCodProduto.setText(this.itemProdutoSelecionado.getId().toString());
                }
                return;
            } else {
                Optional<ItemProduto> item = venda.getItensProdutos().stream().filter(itemProduto -> itemProduto.getId().equals(p.getId())).findAny();
                if (item.isPresent()) {
                    if (JOptionPane.showConfirmDialog(this, "Item selecionado já existe na venda, deseja edita-lo ?",
                            "Atenção", JOptionPane.YES_NO_OPTION) == 1) {
                        return;
                    } else {
                        itemProdutoSelecionado = item.get();
                    }
                } else {
                    this.itemProdutoSelecionado = new ItemProduto();
                    this.itemProdutoSelecionado.buildItem(p);
                }
            }
            this.edtNome.setText(p.getNome());
            //  this.edtValorItem.setValue(p.getPrecoVenda());
            //    this.edtCustoProduto.setValue(p.getPrecoVenda());
            this.edtUnMedida.setText(p.getUnidadeMedida());
            this.edtCodProduto.setText(p.getId().toString());
            //  this.edtValorItem.setValue(p.getPrecoVenda());
            this.edtQuantItem.setValue(1D);
            //this.venda.getItensProdutos().add(itemProdutoSelecionado);
        };
        new PesquisarProduto(this, true, callback).show();
    }//GEN-LAST:event_btnPesquisarItemActionPerformed

    private void btnAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemActionPerformed
        if (itemProdutoSelecionado == null) {
            JOptionPane.showMessageDialog(this, "Nenhum produto foi selecionado");
            return;
        }
        if ((Double) edtQuantItem.getValue() < 1D) {
            JOptionPane.showMessageDialog(this, " A quantidade do produto deve ser no minimo 1");
            this.edtQuantItem.requestFocus();
            return;
        }
        if ((Double) edtCustoProduto.getValue() < 0D) {
            JOptionPane.showMessageDialog(this, "Custo do produto não pode ser menor que 0.00");
            this.edtValorItem.requestFocus();
            return;
        }

        Optional<ItemProduto> itemOptional = venda.getItensProdutos().stream().filter(item -> item.getId().equals(itemProdutoSelecionado.getId())).findAny();
        if (itemOptional.isPresent()) {
            venda.getItensProdutos().remove(itemOptional.get());
        }

        itemProdutoSelecionado.setQuantidade(Util.builDoubleDuasCasasDecimais((Double) edtQuantItem.getValue()));
        itemProdutoSelecionado.setDescontoUnitario(Util.builDoubleDuasCasasDecimais((Double) edtDescItem.getValue()));
        itemProdutoSelecionado.setAcrescimoUnitario(Util.builDoubleDuasCasasDecimais((Double) edtAcrescUn.getValue()));
        itemProdutoSelecionado.setValorUnitario(Util.builDoubleDuasCasasDecimais((Double) edtValorItem.getValue()));

        if (!venda.getItensProdutos().contains(itemProdutoSelecionado))
            this.venda.getItensProdutos().add(itemProdutoSelecionado);

        tableModelProduto.setList(venda.getItensProdutos().toArray());
        tblItens.setModel(tableModelProduto);

        this.atualizaValoTotalVenda(null);

    }//GEN-LAST:event_btnAddItemActionPerformed

    private void btnRemoverItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverItemActionPerformed
        if (tblItens.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "Selecione um item para remover");
            return;
        }
        this.venda.getItensProdutos().remove(tblItens.getSelectedRow());
        this.atualizaValoTotalVenda(null);
        tableModelProduto.setList(venda.getItensProdutos().toArray());
    }//GEN-LAST:event_btnRemoverItemActionPerformed

    private void btnAlterarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarItemActionPerformed
        if (tblItens.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "Selecione um item para editar");
            return;
        }
        this.itemProdutoSelecionado = venda.getItensProdutos().get(tblItens.getSelectedRow());
        this.edtNome.setText(itemProdutoSelecionado.getNome());
        this.edtValorItem.setValue(itemProdutoSelecionado.getValorUnitario());
        this.edtCustoProduto.setValue(itemProdutoSelecionado.getValor());
        this.edtUnMedida.setText(itemProdutoSelecionado.getUnidadeMedida());
        this.edtCodProduto.setText(itemProdutoSelecionado.getId().toString());
        this.venda.getItensProdutos().add(itemProdutoSelecionado);
    }//GEN-LAST:event_btnAlterarItemActionPerformed

    private void btnAlterarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarFornecedorActionPerformed
        PesquisarCliente.Callback callback = (p) -> {
            if (p == null) {
                return;
            }
            //    this.venda.setFornecedor((Fornecedor) p);
            this.edtCliente.setText(p.getNome());
            this.edtCodCliente.setText(p.getId().toString());
            this.venda.setCliente((Cliente) p);
        };

        new PesquisarCliente(this, true, callback).show();
    }//GEN-LAST:event_btnAlterarFornecedorActionPerformed

    private void btnAltCondicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltCondicaoActionPerformed
        PesquisarCondicaoPagamento.Callback callback = (condicao -> {
            if (condicao == null) {
                return;
            }
            if (this.venda.getCondicaoPagamento() != null)
                if (this.venda.getCondicaoPagamento() == condicao)
                    return;
            Optional<CondicaoPagamento> condicaoPagamentoOptional = this.venda.getCliente().getCondicaoPagamentos().stream().filter(condicaoPagamento -> condicao.getId().equals(condicaoPagamento.getId())).findFirst();
            if (!condicaoPagamentoOptional.isPresent()) {
                JOptionPane.showMessageDialog(this, "Condição de pagamento não permitida para o fornecedor selecionado");
                return;
            }
            this.venda.setCondicaoPagamento(condicao);
            edtCondicaoPagamento.setText(condicao.getNome());
            edtCodCondicaoPagamento.setValue(condicao.getId());
            this.buildContas();
        });
        if (this.venda.getCliente() == null) {
            JOptionPane.showMessageDialog(this, "Selecione um cliente");
            return;
        }
        new PesquisarCondicaoPagamento(this, true, callback).show();

    }//GEN-LAST:event_btnAltCondicaoActionPerformed

    //controi as contas a pagar
    public void buildContas() {
        List<Parcela> parcelas = venda.getCondicaoPagamento().getParcelas();
        Double valorTotal = (Double) edtCustoTotal.getValue();
        Integer qtd = parcelas.size();
        Double valor = valorTotal / qtd;
        this.contas.clear();
        Integer pos = 0;
        Integer tam = parcelas.size() - 1;
        for (Parcela parcela : parcelas) {
            ContaReceber conta = new ContaReceber();
            conta.setDataLancamento(new Date());
            Calendar data = new GregorianCalendar();
            data.setTime(new Date());
            data.add(Calendar.DATE, parcela.getDias());
            conta.setDataVencimento(data.getTime());
            conta.setVenda(venda);
            conta.setFormaPagamento(parcela.getFormaPagamento());

            conta.setMulta(venda.getCondicaoPagamento().getMulta());
            conta.setDesconto(venda.getCondicaoPagamento().getDesconto());
            conta.setJuros(venda.getCondicaoPagamento().getJuros());
            conta.setRecebedor(venda.getCliente());
            conta.setDescricao("Conta referente a venda Num. " + venda.getNumeroNota() + ", Ser. " + venda.getNumSerieNota() +
                    ", mod. " + venda.getModeloNota());
            if (pos.equals(tam)) {
                Double valorParcelaFinal = valorTotal - contas.stream().mapToDouble(ContaReceber::getValor).sum();
                conta.setValor(valorParcelaFinal);
            } else {
                conta.setValor(util.Util.builDoubleDuasCasasDecimais(valor -
                        (venda.getCondicaoPagamento().getDesconto() * valor / 100) +
                        (venda.getCondicaoPagamento().getMulta() * valor / 100) +
                        (venda.getCondicaoPagamento().getJuros() * valor / 100))
                );
            }
            pos = pos + 1;
            this.contas.add(conta);
        }
        ;
        this.tableModelContas.setList(contas.toArray());
        this.tblContasApagar.setModel(tableModelContas);
    }

    //metodo que adiciona os itens a venda e adiciona o valor do rateio
    public void buildItens() {
        this.venda.getItensProdutos().stream().forEach(itemProduto -> itemProduto.setVenda(this.venda));
        this.venda.buildRateioItens();
    }

    //função chamada quando alterado os edt que interferem nos valores finais da venda e das parcelas
    // renomer a função para builValores
    private void atualizaValoTotalVenda(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_atualizaValoTotalVenda
        if (venda == null)
            return;

        Double seguro = Util.builDoubleDuasCasasDecimais((Double) edtValorSeguro.getValue());
        Double frete = Util.builDoubleDuasCasasDecimais((Double) edtValorFrete.getValue());
        Double outrasDespesas = Util.builDoubleDuasCasasDecimais((Double) edtOutrasDespesas.getValue());
        Double totaisCustoUn = Util.builDoubleDuasCasasDecimais(venda.getTotaisCustoUn());

        Double total = Util.builDoubleDuasCasasDecimais(totaisCustoUn + frete + outrasDespesas + seguro); //venda.getTotaisCustoUn() + (Double) edtValorSeguro.getValue() + (Double) edtOutrasDespesas.getValue() + (Double) edtValorFrete.getValue();

        edtTotalDescontos.setValue(venda.getTotaisDescontos());
        edtTotalAcrescimos.setValue(venda.getTotaisAcrescimos());
        edtCustoTotal.setValue(total);
        if (venda.getCondicaoPagamento() != null) {
            buildContas();
        }
    }//GEN-LAST:event_atualizaValoTotalVenda

    private void rdTipoFreteCIFItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdTipoFreteCIFItemStateChanged
        if (rdTipoFreteCIF.isSelected()) {
            edtValorFrete.setVisible(false);
            edtValorSeguro.setVisible(false);
            edtOutrasDespesas.setVisible(false);
            lblOutrasDespesas.setVisible(false);
            lblSeguro.setVisible(false);
            lblValorFrete.setVisible(false);
            venda.setTipoFrete(TipoFrete.CIF);
        } else {
            venda.setTipoFrete(TipoFrete.FOB);
            lblSeguro.setVisible(true);
            edtValorFrete.setVisible(true);
            edtValorSeguro.setVisible(true);
            edtOutrasDespesas.setVisible(true);
            lblOutrasDespesas.setVisible(true);
            lblValorFrete.setVisible(true);
        }
    }//GEN-LAST:event_rdTipoFreteCIFItemStateChanged

    private void edtCodProdutoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtCodProdutoKeyPressed
        if (evt.getKeyCode() == KeyCode.ENTER.impl_getCode()) {
            Produto p = null;
            try {
                p = ((Produto) new ProdutoService().getByID(Integer.parseInt(edtCodProduto.getText())));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
            if (p == null) {
                if (itemProdutoSelecionado != null) {
                    edtCodProduto.setText(this.itemProdutoSelecionado.getId().toString());
                }
                return;
            } else {
                Integer id = p.getId();
                Optional<ItemProduto> item = venda.getItensProdutos().stream().filter(itemProduto -> itemProduto.getId().equals(id)).findAny();
                if (item.isPresent()) {
                    if (JOptionPane.showConfirmDialog(this, "Item selecionado já existe na venda, deseja edita-lo ?",
                            "Atenção", JOptionPane.YES_NO_OPTION) == 1) {
                        return;
                    } else {
                        itemProdutoSelecionado = item.get();
                    }
                } else if (!p.getAtivo()) {
                    JOptionPane.showMessageDialog(this, "Produto desativado");
                    return;
                } else {
                    this.itemProdutoSelecionado = new ItemProduto();
                    this.itemProdutoSelecionado.buildItem(p);
                }
            }
            this.edtNome.setText(p.getNome());
            //this.edtCustoProduto.setValue(p.getPrecoVenda());
            this.edtUnMedida.setText(p.getUnidadeMedida());
            this.edtCodProduto.setText(p.getId().toString());
            // this.edtValorItem.setValue(p.getPrecoVenda());
            this.edtQuantItem.setValue(1D);
            this.venda.getItensProdutos().add(itemProdutoSelecionado);
        }
        ;

    }//GEN-LAST:event_edtCodProdutoKeyPressed

    private void edtCodClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtCodClienteKeyPressed
        if (evt.getKeyCode() == KeyCode.ENTER.impl_getCode()) {
            Cliente cliente = null;
            try {
                cliente = ((Cliente) new ClienteService().getByID(Integer.parseInt(edtCodCliente.getText())));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
            if (cliente != null) {
                this.edtCliente.setText(cliente.getNome());
                this.venda.setCliente(cliente);
            } else {
                JOptionPane.showMessageDialog(this, "Nenhhum resultado encontrado");
            }
        }
    }//GEN-LAST:event_edtCodClienteKeyPressed

    private void edtCodCondicaoPagamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtCodCondicaoPagamentoKeyPressed
        if (evt.getKeyCode() == KeyCode.ENTER.impl_getCode()) {
            CondicaoPagamento condicaoPagamento = null;
            try {
                condicaoPagamento = ((CondicaoPagamento) new CondicaoPagamentoService().getByID(Integer.parseInt(edtCodCondicaoPagamento.getText())));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
            if (condicaoPagamento != null) {
                if (venda.getCliente() == null) {
                    JOptionPane.showMessageDialog(this, "Selecione um cliente");
                    return;
                }
                if (!venda.getCliente().getCondicaoPagamentos().contains(condicaoPagamento)) {
                    JOptionPane.showMessageDialog(this, "Condicao de pagamento não permitida para o cliente selecionado");
                    return;
                }
                this.edtCondicaoPagamento.setText(condicaoPagamento.getNome());
                this.venda.setCondicaoPagamento(condicaoPagamento);
            }
        }
    }//GEN-LAST:event_edtCodCondicaoPagamentoKeyPressed

    private void calculaValorTotalPorItem(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_calculaValorTotalPorItem
        Double qtd = (Double) edtQuantItem.getValue();
        Double valorItem = (Double) edtValorItem.getValue();
        Double descUn = (Double) edtDescItem.getValue();
        Double acresUn = (Double) edtAcrescUn.getValue();
        edtCustoProduto.setValue((valorItem * qtd) - (descUn * qtd) + (acresUn * qtd));
    }//GEN-LAST:event_calculaValorTotalPorItem

    private void validaNota(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_validaNota
        if (edtNumeroNota.getText().trim().isEmpty() || edtModeloNota.getText().trim().isEmpty() || edtModeloNota.getText().trim().isEmpty()) {
            if (!camposBloquados)
                bloqueia();
            return;
        }
        Integer num = Integer.parseInt(edtNumeroNota.getValue().toString());
        String modelo = edtModeloNota.getText();
        Integer serie = Integer.parseInt(edtNumeroSerie.getValue().toString());
        try {
            if (new VendaProdutoService().getByNumSerieModelo(num, modelo, serie) != null) {
                if (!camposBloquados)
                    bloqueia();
                //JOptionPane.showMessageDialog(this, "Código da venda já esta em uso");
            } else if (camposBloquados)
                desbloqueia();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_validaNota

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnAltCondicao;
    private javax.swing.JButton btnAlterarFornecedor;
    private javax.swing.JButton btnAlterarItem;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnPesquisarItem;
    private javax.swing.JButton btnRemoverItem;
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JFormattedTextField edtAcrescUn;
    private javax.swing.JTextField edtCliente;
    private javax.swing.JFormattedTextField edtCodCliente;
    private javax.swing.JFormattedTextField edtCodCondicaoPagamento;
    private javax.swing.JFormattedTextField edtCodProduto;
    private javax.swing.JTextField edtCondicaoPagamento;
    private javax.swing.JFormattedTextField edtCustoProduto;
    private javax.swing.JFormattedTextField edtCustoTotal;
    private javax.swing.JFormattedTextField edtDescItem;
    private com.toedter.calendar.JDateChooser edtDtChegada;
    private com.toedter.calendar.JDateChooser edtDtEmissão;
    private javax.swing.JTextField edtFuncionario;
    private javax.swing.JFormattedTextField edtModeloNota;
    private javax.swing.JTextField edtNome;
    private javax.swing.JFormattedTextField edtNumeroNota;
    private javax.swing.JFormattedTextField edtNumeroSerie;
    private javax.swing.JFormattedTextField edtOutrasDespesas;
    private javax.swing.JFormattedTextField edtQuantItem;
    private javax.swing.JFormattedTextField edtTotalAcrescimos;
    private javax.swing.JFormattedTextField edtTotalDescontos;
    private javax.swing.JTextField edtUnMedida;
    private javax.swing.JFormattedTextField edtValorFrete;
    private javax.swing.JFormattedTextField edtValorItem;
    private javax.swing.JFormattedTextField edtValorSeguro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAcrescUn;
    private javax.swing.JLabel lblCodProd;
    private javax.swing.JLabel lblCusto;
    private javax.swing.JLabel lblCustoProd;
    private javax.swing.JLabel lblDescUn;
    private javax.swing.JLabel lblDescricaoForm;
    private javax.swing.JLabel lblDescricaoForm1;
    private javax.swing.JLabel lblOutrasDespesas;
    private javax.swing.JLabel lblProd;
    private javax.swing.JLabel lblSeguro;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblUn;
    private javax.swing.JLabel lblValorFrete;
    private javax.swing.JLabel lblqtd;
    private javax.swing.JRadioButton rdFreteFOB;
    private javax.swing.JRadioButton rdTipoFreteCIF;
    private javax.swing.JTable tblContasApagar;
    private javax.swing.JTable tblItens;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
