/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.*;

import gui.comercial.compra.ConsultaCompraForm;
import gui.enderecos.cidades.ConsultaCidades;
import gui.enderecos.estados.ConsultaEstados;
import gui.enderecos.pais.ConsultaPaises;
import gui.financeiro.CondicaoPagamento.ConsultaCondicoesPagamentoForm;
import gui.financeiro.caixas.ConsultarCaixaForm;
import gui.financeiro.contas.contas_a_pagar.ConsultaContasAPagar;
import gui.financeiro.formaPagamento.ConsultaFormasPagamentos;
import gui.grupo.ConsultaGrupoForm;
import gui.marca.ConsultarMarca;
import gui.operador.CadastrarFuncionario;
import gui.operador.ConsultaFuncionarioForm;
import gui.operador.login;
import gui.pessoas.clientes.ConsultaClientesForm;
import gui.pessoas.clientes.NovoClienteForm;
import gui.pessoas.fornecedores.ConsultaFornecedoresForm;
import gui.produtos.*;
import gui.servicos.ConsultaServicos;
import gui.sistema.CadastroGrupoOperadores;
import gui.sistema.ConsultaGruposOperadoresForm;
import gui.sistema.PanelPrincipal;
import gui.swing.ButtonTabComponent;
import lib.dao.AbstractDao;
import lib.model.interno.Funcionario;
import lib.model.pessoa.cliente.Cliente;

import java.sql.SQLException;

/**
 *
 * @author Diego
 */
public class janelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form janelaPrincipal
     */
    public janelaPrincipal() {
        initComponents();
    this.jTabbedPane1.add("Pagina Principal", new PanelPrincipal());
    }

    public Integer verrificaJanelaAberta(String name){
        Integer tam = jTabbedPane1.getTabCount();
        Integer i = 0;
        while (i<tam){
            if (jTabbedPane1.getTitleAt(i) == name){
                return i;
            }
            i++;
        }
        return null;
    }

    public void setOperador(Funcionario operador){
        if (operador == null)
            edtoperador.setText("Suporte");
        else
            edtoperador.setText(operador.getNome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu4 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu19 = new javax.swing.JMenu();
        jMenu20 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu22 = new javax.swing.JMenu();
        jMenu23 = new javax.swing.JMenu();
        jMenuBar5 = new javax.swing.JMenuBar();
        jMenu24 = new javax.swing.JMenu();
        jMenu25 = new javax.swing.JMenu();
        jMenuBar6 = new javax.swing.JMenuBar();
        jMenu26 = new javax.swing.JMenu();
        jMenu27 = new javax.swing.JMenu();
        jMenu28 = new javax.swing.JMenu();
        jMenuBar7 = new javax.swing.JMenuBar();
        jMenu29 = new javax.swing.JMenu();
        jMenu30 = new javax.swing.JMenu();
        jMenuBar8 = new javax.swing.JMenuBar();
        jMenu31 = new javax.swing.JMenu();
        jMenu32 = new javax.swing.JMenu();
        jMenuBar9 = new javax.swing.JMenuBar();
        jMenu33 = new javax.swing.JMenu();
        jMenu34 = new javax.swing.JMenu();
        jSeparator3 = new javax.swing.JSeparator();
        jMenuBar10 = new javax.swing.JMenuBar();
        jMenu35 = new javax.swing.JMenu();
        jMenu36 = new javax.swing.JMenu();
        jDialog1 = new javax.swing.JDialog();
        jMenu37 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar11 = new javax.swing.JMenuBar();
        jMenu38 = new javax.swing.JMenu();
        jMenu39 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jPopupMenu4 = new javax.swing.JPopupMenu();
        jPopupMenu5 = new javax.swing.JPopupMenu();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jYearChooser1 = new com.toedter.calendar.JYearChooser();
        jDesktopPane = new javax.swing.JDesktopPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        btnNovoCliente = new javax.swing.JButton();
        btnNovaCompraAcessoRpd = new javax.swing.JButton();
        btnNovaVenda = new javax.swing.JToggleButton();
        btnNovoOrcamento = new javax.swing.JButton();
        edtoperador = new javax.swing.JTextField();
        btnTrocar = new javax.swing.JButton();
        btnsair = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu18 = new javax.swing.JMenu();
        mnuPaises = new javax.swing.JMenuItem();
        mnuEstados = new javax.swing.JMenuItem();
        mnuCidades = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        mnuconsClientes = new javax.swing.JMenuItem();
        ConsultarFornecedor = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mnuConsultarProd = new javax.swing.JMenuItem();
        mnuConsultaServico = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mnuGrupos = new javax.swing.JMenuItem();
        mnuConsultarMarca = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu13 = new javax.swing.JMenu();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        mnuItemCondicaoPagamento = new javax.swing.JMenuItem();
        itmMnuFormaPagamento = new javax.swing.JMenuItem();
        mnuContasPagar = new javax.swing.JMenuItem();
        mnuCaixas = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        btnCompras = new javax.swing.JMenuItem();
        btnVenda = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mnuOperadores = new javax.swing.JMenuItem();
        mnuGrupoFuncionarios = new javax.swing.JMenuItem();
        jMenu16 = new javax.swing.JMenu();
        mnuConsultaOperador = new javax.swing.JMenuItem();
        mnuCadOperador = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuConsultaGrupos = new javax.swing.JMenuItem();
        mnuCadGrupo = new javax.swing.JMenuItem();

        jMenu4.setText("jMenu4");

        jMenu1.setText("jMenu1");

        jMenu6.setText("jMenu6");

        jMenu7.setText("File");
        jMenuBar2.add(jMenu7);

        jMenu8.setText("Edit");
        jMenuBar2.add(jMenu8);

        jMenu9.setText("File");
        jMenuBar3.add(jMenu9);

        jMenu10.setText("Edit");
        jMenuBar3.add(jMenu10);

        jMenu12.setText("jMenu12");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem3.setText("jMenuItem3");

        jMenu19.setText("jMenu19");

        jMenu20.setText("jMenu20");

        jMenu22.setText("File");
        jMenuBar4.add(jMenu22);

        jMenu23.setText("Edit");
        jMenuBar4.add(jMenu23);

        jMenu24.setText("File");
        jMenuBar5.add(jMenu24);

        jMenu25.setText("Edit");
        jMenuBar5.add(jMenu25);

        jMenu26.setText("File");
        jMenuBar6.add(jMenu26);

        jMenu27.setText("Edit");
        jMenuBar6.add(jMenu27);

        jMenu28.setText("jMenu28");

        jMenu29.setText("File");
        jMenuBar7.add(jMenu29);

        jMenu30.setText("Edit");
        jMenuBar7.add(jMenu30);

        jMenu31.setText("File");
        jMenuBar8.add(jMenu31);

        jMenu32.setText("Edit");
        jMenuBar8.add(jMenu32);

        jMenu33.setText("File");
        jMenuBar9.add(jMenu33);

        jMenu34.setText("Edit");
        jMenuBar9.add(jMenu34);

        jMenu35.setText("File");
        jMenuBar10.add(jMenu35);

        jMenu36.setText("Edit");
        jMenuBar10.add(jMenu36);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jMenu37.setText("jMenu37");

        jMenuItem2.setText("jMenuItem2");

        jMenu38.setText("File");
        jMenuBar11.add(jMenu38);

        jMenu39.setText("Edit");
        jMenuBar11.add(jMenu39);

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jDesktopPane.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPaneLayout.setVerticalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        btnNovoCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNovoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/business_application_addmale_useradd_insert_add_user_client_2312.png"))); // NOI18N
        btnNovoCliente.setText("Novo Cliente");
        btnNovoCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoClienteActionPerformed(evt);
            }
        });

        btnNovaCompraAcessoRpd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNovaCompraAcessoRpd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shoppingcart_to_compra_12829 (1).png"))); // NOI18N
        btnNovaCompraAcessoRpd.setText("Nova Compra");
        btnNovaCompraAcessoRpd.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNovaCompraAcessoRpd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaCompraAcessoRpdActionPerformed(evt);
            }
        });

        btnNovaVenda.setBackground(new java.awt.Color(255, 255, 255));
        btnNovaVenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNovaVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shoppingcart_below_compra_12831 (1).png"))); // NOI18N
        btnNovaVenda.setText("Nova fatura");
        btnNovaVenda.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNovaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaVendaActionPerformed(evt);
            }
        });

        btnNovoOrcamento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNovoOrcamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/construction_project_plan_building_architect_design_develop-71_icon-icons.com_60239.png"))); // NOI18N
        btnNovoOrcamento.setText("Novo orçamento");
        btnNovoOrcamento.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNovoOrcamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoOrcamentoActionPerformed(evt);
            }
        });

        edtoperador.setEditable(false);

        btnTrocar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTrocar.setText("trocar");
        btnTrocar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrocarActionPerformed(evt);
            }
        });

        btnsair.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnsair.setText("sair");
        btnsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsairActionPerformed(evt);
            }
        });

        jMenu18.setBackground(new java.awt.Color(255, 255, 255));
        jMenu18.setText("Cadastros");
        jMenu18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        mnuPaises.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mnuPaises.setText("Países");
        mnuPaises.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPaisesActionPerformed(evt);
            }
        });
        jMenu18.add(mnuPaises);

        mnuEstados.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mnuEstados.setText("Estados");
        mnuEstados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEstadosActionPerformed(evt);
            }
        });
        jMenu18.add(mnuEstados);

        mnuCidades.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mnuCidades.setText("Cidades");
        mnuCidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCidadesActionPerformed(evt);
            }
        });
        jMenu18.add(mnuCidades);
        jMenu18.add(jSeparator6);

        mnuconsClientes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mnuconsClientes.setText("Clientes ");
        mnuconsClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuconsClientesActionPerformed(evt);
            }
        });
        jMenu18.add(mnuconsClientes);

        ConsultarFornecedor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ConsultarFornecedor.setText("Fornecedores");
        ConsultarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarFornecedorActionPerformed(evt);
            }
        });
        jMenu18.add(ConsultarFornecedor);

        jMenuBar1.add(jMenu18);

        jMenu3.setBackground(new java.awt.Color(255, 255, 255));
        jMenu3.setBorder(null);
        jMenu3.setText("Produtos e serviços");
        jMenu3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenu3.add(jSeparator5);

        mnuConsultarProd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mnuConsultarProd.setText("Produtos");
        mnuConsultarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConsultarProdActionPerformed(evt);
            }
        });
        jMenu3.add(mnuConsultarProd);

        mnuConsultaServico.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mnuConsultaServico.setText("Serviços");
        mnuConsultaServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConsultaServicoActionPerformed(evt);
            }
        });
        jMenu3.add(mnuConsultaServico);
        jMenu3.add(jSeparator4);

        mnuGrupos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mnuGrupos.setText("Grupos");
        mnuGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGruposActionPerformed(evt);
            }
        });
        jMenu3.add(mnuGrupos);

        mnuConsultarMarca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mnuConsultarMarca.setText("Marcas");
        mnuConsultarMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConsultarMarcaActionPerformed(evt);
            }
        });
        jMenu3.add(mnuConsultarMarca);
        jMenu3.add(jSeparator1);

        jMenuBar1.add(jMenu3);

        jMenu13.setText("Financeiro");
        jMenu13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenu13.add(jSeparator7);

        mnuItemCondicaoPagamento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mnuItemCondicaoPagamento.setText("Condições de pagamentos");
        mnuItemCondicaoPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemCondicaoPagamentoActionPerformed(evt);
            }
        });
        jMenu13.add(mnuItemCondicaoPagamento);

        itmMnuFormaPagamento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itmMnuFormaPagamento.setText("Formas de pagamento");
        itmMnuFormaPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmMnuFormaPagamentoActionPerformed(evt);
            }
        });
        jMenu13.add(itmMnuFormaPagamento);

        mnuContasPagar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mnuContasPagar.setText("Contas a pagar");
        mnuContasPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuContasPagarActionPerformed(evt);
            }
        });
        jMenu13.add(mnuContasPagar);

        mnuCaixas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mnuCaixas.setText("Caixas");
        mnuCaixas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCaixasActionPerformed(evt);
            }
        });
        jMenu13.add(mnuCaixas);

        jMenuBar1.add(jMenu13);

        jMenu2.setText("Comercial");
        jMenu2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnCompras.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCompras.setText("Compras");
        btnCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprasActionPerformed(evt);
            }
        });
        jMenu2.add(btnCompras);

        btnVenda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVenda.setText("Vendas");
        btnVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendaActionPerformed(evt);
            }
        });
        jMenu2.add(btnVenda);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Sistema");
        jMenu5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        mnuOperadores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mnuOperadores.setText("Funcionarios");
        mnuOperadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuOperadoresActionPerformed(evt);
            }
        });
        jMenu5.add(mnuOperadores);

        mnuGrupoFuncionarios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mnuGrupoFuncionarios.setText("Grupos de funcionarios");
        mnuGrupoFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGrupoFuncionariosActionPerformed(evt);
            }
        });
        jMenu5.add(mnuGrupoFuncionarios);

        jMenuBar1.add(jMenu5);

        jMenu16.setEnabled(false);

        mnuConsultaOperador.setText("Operadores");
        mnuConsultaOperador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConsultaOperadorActionPerformed(evt);
            }
        });
        jMenu16.add(mnuConsultaOperador);

        mnuCadOperador.setText("Cadastrar operador");
        mnuCadOperador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadOperadorActionPerformed(evt);
            }
        });
        jMenu16.add(mnuCadOperador);
        jMenu16.add(jSeparator2);

        mnuConsultaGrupos.setText("Grupos");
        mnuConsultaGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConsultaGruposActionPerformed(evt);
            }
        });
        jMenu16.add(mnuConsultaGrupos);

        mnuCadGrupo.setText("Cadastrar grupo");
        mnuCadGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadGrupoActionPerformed(evt);
            }
        });
        jMenu16.add(mnuCadGrupo);

        jMenuBar1.add(jMenu16);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(jDesktopPane))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNovaVenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNovaCompraAcessoRpd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNovoCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNovoOrcamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTrocar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnsair))
                    .addComponent(edtoperador, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(edtoperador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTrocar)
                            .addComponent(btnsair)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNovoCliente)
                        .addComponent(btnNovaCompraAcessoRpd, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnNovaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnNovoOrcamento)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoOrcamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoOrcamentoActionPerformed
      //  new OrcamentoForm(this,true,new Orcamento()).show();
    }//GEN-LAST:event_btnNovoOrcamentoActionPerformed

    private void btnNovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoClienteActionPerformed
        Cliente pessoa = new Cliente();
        NovoClienteForm novaPessoaForm = new NovoClienteForm(this, true, pessoa);
        novaPessoaForm.show();
    }//GEN-LAST:event_btnNovoClienteActionPerformed

    private void btnTrocarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrocarActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Deseja realmente trocar o operador do do sistema ?", "Atenção", JOptionPane.YES_NO_OPTION)==0)
            new login(this,true).setVisible(true);
        else
            return;
    }//GEN-LAST:event_btnTrocarActionPerformed

    private void btnsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsairActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Deseja realmente sair do sistema ?", "Atenção", JOptionPane.YES_NO_OPTION)==0) {
            try {
                AbstractDao.st.getConnection().close();
                System.exit(0);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_btnsairActionPerformed

    private void mnuEstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEstadosActionPerformed
        ConsultaEstados p=new ConsultaEstados(this);
        Integer i = verrificaJanelaAberta("Estados");
        if (i != null){
            jTabbedPane1.setSelectedIndex(i);
            return;
        }
        jTabbedPane1.addTab("Estados", p);
        jTabbedPane1.setSelectedComponent(p);
        i = jTabbedPane1.getSelectedIndex();
        jTabbedPane1.setTabComponentAt(i, new ButtonTabComponent(jTabbedPane1));
    }//GEN-LAST:event_mnuEstadosActionPerformed

    private void mnuPaisesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPaisesActionPerformed
        ConsultaPaises p=new ConsultaPaises(this);
        Integer i = verrificaJanelaAberta("Países");
        if (i != null){
            jTabbedPane1.setSelectedIndex(i);
            return;
        }
        jTabbedPane1.addTab("Países", p);
        jTabbedPane1.setSelectedComponent(p);
        i = jTabbedPane1.getSelectedIndex();
        jTabbedPane1.setTabComponentAt(i, new ButtonTabComponent(jTabbedPane1));
    }//GEN-LAST:event_mnuPaisesActionPerformed

    private void mnuCidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCidadesActionPerformed
        ConsultaCidades p=new ConsultaCidades(this);
        Integer i = verrificaJanelaAberta("Cidades");
        if (i != null){
            jTabbedPane1.setSelectedIndex(i);
            return;
        }
        jTabbedPane1.addTab("Cidades", p);
        jTabbedPane1.setSelectedComponent(p);
        i = jTabbedPane1.getSelectedIndex();
        jTabbedPane1.setTabComponentAt(i, new ButtonTabComponent(jTabbedPane1));
    }//GEN-LAST:event_mnuCidadesActionPerformed

    private void ConsultarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarFornecedorActionPerformed
        ConsultaFornecedoresForm p=new ConsultaFornecedoresForm(this);
        Integer i = verrificaJanelaAberta("Fornecedores");
        if (i != null){
            jTabbedPane1.setSelectedIndex(i);
            return;
        }
        jTabbedPane1.addTab("Fornecedores", p);
        jTabbedPane1.setSelectedComponent(p);
        i = jTabbedPane1.getSelectedIndex();
        jTabbedPane1.setTabComponentAt(i, new ButtonTabComponent(jTabbedPane1));
    }//GEN-LAST:event_ConsultarFornecedorActionPerformed

    private void mnuGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGruposActionPerformed
        ConsultaGrupoForm p=new ConsultaGrupoForm(this);
        Integer i = verrificaJanelaAberta("Grupos de produtos e serviços");
        if (i != null){
            jTabbedPane1.setSelectedIndex(i);
            return;
        }
        jTabbedPane1.addTab("Grupos de produtos e serviços", p);
        jTabbedPane1.setSelectedComponent(p);
        i = jTabbedPane1.getSelectedIndex();
        jTabbedPane1.setTabComponentAt(i, new ButtonTabComponent(jTabbedPane1));
    }//GEN-LAST:event_mnuGruposActionPerformed

    private void mnuItemCondicaoPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemCondicaoPagamentoActionPerformed
        ConsultaCondicoesPagamentoForm p = new ConsultaCondicoesPagamentoForm(this);
        Integer i = verrificaJanelaAberta("Condições de pagamento");
        if (i != null){
            jTabbedPane1.setSelectedIndex(i);
            return;
        }
        jTabbedPane1.addTab("Condições de pagamento", p);
        jTabbedPane1.setSelectedComponent(p);
        i = jTabbedPane1.getSelectedIndex();
        jTabbedPane1.setTabComponentAt(i, new ButtonTabComponent(jTabbedPane1));
    }//GEN-LAST:event_mnuItemCondicaoPagamentoActionPerformed

    private void itmMnuFormaPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmMnuFormaPagamentoActionPerformed
        ConsultaFormasPagamentos p=new ConsultaFormasPagamentos(this);
        Integer i = verrificaJanelaAberta("Formas de pagamento");
        if (i != null){
            jTabbedPane1.setSelectedIndex(i);
            return;
        }
        jTabbedPane1.addTab("Formas de pagamento", p);
        jTabbedPane1.setSelectedComponent(p);
        i = jTabbedPane1.getSelectedIndex();
        jTabbedPane1.setTabComponentAt(i, new ButtonTabComponent(jTabbedPane1));

    }//GEN-LAST:event_itmMnuFormaPagamentoActionPerformed

    private void btnComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprasActionPerformed
        ConsultaCompraForm p=new ConsultaCompraForm(this);
        Integer i = verrificaJanelaAberta("Compras");
        if (i != null){
            jTabbedPane1.setSelectedIndex(i);
            return;
        }
        jTabbedPane1.addTab("Compras", p);
        jTabbedPane1.setSelectedComponent(p);
        i = jTabbedPane1.getSelectedIndex();
        jTabbedPane1.setTabComponentAt(i, new ButtonTabComponent(jTabbedPane1));
    }//GEN-LAST:event_btnComprasActionPerformed

    private void btnVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVendaActionPerformed

    private void mnuContasPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuContasPagarActionPerformed
        ConsultaContasAPagar p=new ConsultaContasAPagar(this);
        Integer i = verrificaJanelaAberta("Contas a pagar");
        if (i != null){
            jTabbedPane1.setSelectedIndex(i);
            return;
        }
        jTabbedPane1.addTab("Contas a pagar", p);
        jTabbedPane1.setSelectedComponent(p);
        i = jTabbedPane1.getSelectedIndex();
        jTabbedPane1.setTabComponentAt(i, new ButtonTabComponent(jTabbedPane1));
    }//GEN-LAST:event_mnuContasPagarActionPerformed

    private void mnuCaixasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCaixasActionPerformed
       ConsultarCaixaForm p = new ConsultarCaixaForm(this);
       Integer i = verrificaJanelaAberta("Caixas");
        if (i != null){
            jTabbedPane1.setSelectedIndex(i);
            return;
        }
        jTabbedPane1.addTab("Caixas", p);
        jTabbedPane1.setSelectedComponent(p);
        i = jTabbedPane1.getSelectedIndex();
        jTabbedPane1.setTabComponentAt(i, new ButtonTabComponent(jTabbedPane1));
    }//GEN-LAST:event_mnuCaixasActionPerformed

    private void mnuOperadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuOperadoresActionPerformed
       ConsultaFuncionarioForm p = new ConsultaFuncionarioForm(this);
       Integer i = verrificaJanelaAberta("Funcionarios");
        if (i != null){
            jTabbedPane1.setSelectedIndex(i);
            return;
        }
        jTabbedPane1.addTab("Funcionarios", p);
        jTabbedPane1.setSelectedComponent(p);
        i = jTabbedPane1.getSelectedIndex();
        jTabbedPane1.setTabComponentAt(i, new ButtonTabComponent(jTabbedPane1));
    }//GEN-LAST:event_mnuOperadoresActionPerformed

    private void mnuGrupoFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGrupoFuncionariosActionPerformed
        ConsultaGruposOperadoresForm p = new ConsultaGruposOperadoresForm(this);
        Integer i = verrificaJanelaAberta("Grupos de funcionarios");
        if (i != null){
            jTabbedPane1.setSelectedIndex(i);
            return;
        }
        jTabbedPane1.addTab("Grupos de funcionarios", p);
        jTabbedPane1.setSelectedComponent(p);
        i = jTabbedPane1.getSelectedIndex();
        jTabbedPane1.setTabComponentAt(i, new ButtonTabComponent(jTabbedPane1));
    }//GEN-LAST:event_mnuGrupoFuncionariosActionPerformed

    private void btnNovaCompraAcessoRpdActionPerformed(java.awt.event.ActionEvent evt) {
      //  new NovaCompraForm(this, true, new Compra()).show();
    }

    private void btnNovaVendaActionPerformed(java.awt.event.ActionEvent evt) {
       // new NovaVendaForm(this, true, new Venda()).show();
    }                                            

    private void mnuConsultaServicoActionPerformed(java.awt.event.ActionEvent evt) {
        ConsultaServicos p=new ConsultaServicos(this);
        Integer i = verrificaJanelaAberta("Servicos");
        if (i != null){
            jTabbedPane1.setSelectedIndex(i);
            return;
        }
        jTabbedPane1.addTab("Servicos", p);
        jTabbedPane1.setSelectedComponent(p);
        i = jTabbedPane1.getSelectedIndex();
        jTabbedPane1.setTabComponentAt(i, new ButtonTabComponent(jTabbedPane1));
    }


    private void mnuCadServicoActionPerformed(java.awt.event.ActionEvent evt) {

    }


    private void mnuConsultaGruposActionPerformed(java.awt.event.ActionEvent evt) {
        ConsultaGruposOperadoresForm obj=new ConsultaGruposOperadoresForm(this);
        Integer i = verrificaJanelaAberta("Grupo de operadores");
        if (i != null){
            jTabbedPane1.setSelectedIndex(i);
            return;
        }
        jTabbedPane1.addTab("Grupo de operadores", obj);
        jTabbedPane1.setSelectedComponent(obj);
        i = jTabbedPane1.getSelectedIndex();
        jTabbedPane1.setTabComponentAt(i, new ButtonTabComponent(jTabbedPane1));
    }

    private void mnuCadOperadorActionPerformed(java.awt.event.ActionEvent evt) {
        CadastrarFuncionario cadastrarOperador=new CadastrarFuncionario(this, true, new Funcionario());
        cadastrarOperador.show();
    }

    private void mnuCadGrupoActionPerformed(java.awt.event.ActionEvent evt) {
        CadastroGrupoOperadores cadastroGrupoOperadores=new CadastroGrupoOperadores(this, true,null);
        cadastroGrupoOperadores.show();
    }

    private void mnuConsultaOperadorActionPerformed(java.awt.event.ActionEvent evt) {
        ConsultaFuncionarioForm p=new ConsultaFuncionarioForm(this);
        Integer i = verrificaJanelaAberta("Operadores");
        if (i != null){
            jTabbedPane1.setSelectedIndex(i);
            return;
        }
        jTabbedPane1.addTab("Operadores", p);
        jTabbedPane1.setSelectedComponent(p);
        i = jTabbedPane1.getSelectedIndex();
        jTabbedPane1.setTabComponentAt(i, new ButtonTabComponent(jTabbedPane1));
    }

    private void mnuconsClientesActionPerformed(java.awt.event.ActionEvent evt) {
    	ConsultaClientesForm p=new ConsultaClientesForm(this);
        Integer i = verrificaJanelaAberta("Clientes");
        if (i != null){
            jTabbedPane1.setSelectedIndex(i);
            return;
        }
        jTabbedPane1.addTab("Clientes", p);
        jTabbedPane1.setSelectedComponent(p);
        i = jTabbedPane1.getSelectedIndex();
        jTabbedPane1.setTabComponentAt(i, new ButtonTabComponent(jTabbedPane1));
    }

    private void mnuConsultarProdActionPerformed(java.awt.event.ActionEvent evt) {
        ConsultaProdutosForm consultaProdutosForm = new ConsultaProdutosForm(this);
        Integer i = verrificaJanelaAberta("Produtos");
        if (i != null) {
            jTabbedPane1.setSelectedIndex(i);
            return;
        }
        jTabbedPane1.addTab("Produtos", consultaProdutosForm);
        jTabbedPane1.setSelectedComponent(consultaProdutosForm);
        i = jTabbedPane1.getSelectedIndex();
        jTabbedPane1.setTabComponentAt(i, new ButtonTabComponent(jTabbedPane1));
    }

    private void mnuConsultarMarcaActionPerformed(java.awt.event.ActionEvent evt) {
        ConsultarMarca obj=new ConsultarMarca(this);
        jTabbedPane1.addTab("Marcas", obj);
        jTabbedPane1.setSelectedComponent(obj);
        int i = jTabbedPane1.getSelectedIndex();
        jTabbedPane1.setTabComponentAt(i, new ButtonTabComponent(jTabbedPane1));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(janelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(janelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(janelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(janelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new janelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ConsultarFornecedor;
    private javax.swing.JMenuItem btnCompras;
    private javax.swing.JButton btnNovaCompraAcessoRpd;
    private javax.swing.JToggleButton btnNovaVenda;
    private javax.swing.JButton btnNovoCliente;
    private javax.swing.JButton btnNovoOrcamento;
    private javax.swing.JButton btnTrocar;
    private javax.swing.JMenuItem btnVenda;
    private javax.swing.JButton btnsair;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField edtoperador;
    private javax.swing.JMenuItem itmMnuFormaPagamento;
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu19;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu20;
    private javax.swing.JMenu jMenu22;
    private javax.swing.JMenu jMenu23;
    private javax.swing.JMenu jMenu24;
    private javax.swing.JMenu jMenu25;
    private javax.swing.JMenu jMenu26;
    private javax.swing.JMenu jMenu27;
    private javax.swing.JMenu jMenu28;
    private javax.swing.JMenu jMenu29;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu30;
    private javax.swing.JMenu jMenu31;
    private javax.swing.JMenu jMenu32;
    private javax.swing.JMenu jMenu33;
    private javax.swing.JMenu jMenu34;
    private javax.swing.JMenu jMenu35;
    private javax.swing.JMenu jMenu36;
    private javax.swing.JMenu jMenu37;
    private javax.swing.JMenu jMenu38;
    private javax.swing.JMenu jMenu39;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar10;
    private javax.swing.JMenuBar jMenuBar11;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JMenuBar jMenuBar6;
    private javax.swing.JMenuBar jMenuBar7;
    private javax.swing.JMenuBar jMenuBar8;
    private javax.swing.JMenuBar jMenuBar9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JPopupMenu jPopupMenu4;
    private javax.swing.JPopupMenu jPopupMenu5;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private com.toedter.calendar.JYearChooser jYearChooser1;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private javax.swing.JMenuItem mnuCadGrupo;
    private javax.swing.JMenuItem mnuCadOperador;
    private javax.swing.JMenuItem mnuCaixas;
    private javax.swing.JMenuItem mnuCidades;
    private javax.swing.JMenuItem mnuConsultaGrupos;
    private javax.swing.JMenuItem mnuConsultaOperador;
    private javax.swing.JMenuItem mnuConsultaServico;
    private javax.swing.JMenuItem mnuConsultarMarca;
    private javax.swing.JMenuItem mnuConsultarProd;
    private javax.swing.JMenuItem mnuContasPagar;
    private javax.swing.JMenuItem mnuEstados;
    private javax.swing.JMenuItem mnuGrupoFuncionarios;
    private javax.swing.JMenuItem mnuGrupos;
    private javax.swing.JMenuItem mnuItemCondicaoPagamento;
    private javax.swing.JMenuItem mnuOperadores;
    private javax.swing.JMenuItem mnuPaises;
    private javax.swing.JMenuItem mnuconsClientes;
    // End of variables declaration//GEN-END:variables
}
