/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.grupo;

import gui.modeltable.TableModelGrupo;
import gui.sistema.CadastroGrupoOperadores;
import gui.swing.SociusTab;
import gui.swing.WindowPadrao;
import lib.model.grupo.Grupo;
import lib.model.interno.ModuloSistema;
import lib.service.GrupoService;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Diego
 */
public class ConsultaGrupoForm extends SociusTab implements WindowPadrao {

    private Grupo grupoSelecionado;
    private List<Grupo> grupos;
    private TableModelGrupo tableModelGrupo;
    private GrupoService grupoService;
    private CadastrarGrupoForm cadastrarGrupoForm;


    /**
     * Creates new form ConsultaPanel
     */
    public ConsultaGrupoForm(Window parent) {
        super(parent, ModuloSistema.PESSOAS);
        initComponents();
        grupos=new ArrayList<>();
        grupoService=new GrupoService();
        tableModelGrupo=new TableModelGrupo();
        jButton1ActionPerformed(null);
        initTable();
        if (!grupos.isEmpty())
            jTable1.setRowSelectionInterval(0,0);
    }

    public void initTable(){
        this.jTable1.getColumnModel().getColumn(0).setPreferredWidth(100);
        this.jTable1.getColumnModel().getColumn(1).setPreferredWidth(500);
        this.jTable1.getColumnModel().getColumn(2).setPreferredWidth(100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        edtPesquisa = new javax.swing.JTextField();
        btnNovo = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnVisualizar = new javax.swing.JButton();
        btnExcluirDesativar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setName("Consulta"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnAlterar.setText("alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnVisualizar.setText("visualizar");
        btnVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarActionPerformed(evt);
            }
        });

        btnExcluirDesativar.setText("excluir");
        btnExcluirDesativar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirDesativarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(edtPesquisa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluirDesativar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(edtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnAlterar)
                    .addComponent(btnVisualizar)
                    .addComponent(btnExcluirDesativar))
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirDesativarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirDesativarActionPerformed
        if (jTable1.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "Selecione um registro para continuar");
            return;
        }
        grupoSelecionado=grupos.get(jTable1.getSelectedRow());
        CadastrarGrupoForm cadastrarGrupoForm = new CadastrarGrupoForm(getWindowParent(), true, grupoSelecionado, null);
        cadastrarGrupoForm.carregaEdt();
        cadastrarGrupoForm.bloqueiaedt();
        cadastrarGrupoForm.show();
        try {
            grupoService.deleteByID(grupoSelecionado.getId());
            if (JOptionPane.showConfirmDialog(this, "Deseja realmente excluir o grupo selecionado ?", "Atenção", JOptionPane.YES_NO_OPTION) != 0) {
                cadastrarGrupoForm.dispose();
                return;
            }
            JOptionPane.showMessageDialog(this, "Excluido com sucesso");

        } catch (Exception e) {
            if (JOptionPane.showConfirmDialog(this,"Não é possivel excluir o registro, deseja desativa-lo?", "ATENÇÂO", JOptionPane.YES_NO_OPTION)==0) {
                if (!grupoSelecionado.getAtivo())
                    JOptionPane.showMessageDialog(this, "Pessoa já está desativada");
                try {
                    grupoService.update(grupoSelecionado);
                    JOptionPane.showMessageDialog(this,
                            "Desativado com sucesso"
                    );
                    grupos = new GrupoService().getAll("");
                } catch (Exception e1) {
                    JOptionPane.showMessageDialog(this, "Não foi possivel desativar");
                }
            }
        }
        try {
            grupos = new GrupoService().getAll("");
        } catch (Exception ex){}
        tableModelGrupo.setList(grupos.toArray());
        jTable1.setModel(tableModelGrupo);
        cadastrarGrupoForm.dispose();
    }//GEN-LAST:event_btnExcluirDesativarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            grupos = grupoService.getAll(edtPesquisa.getText());
        } catch (Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
            return;
        }
        tableModelGrupo.setList(this.grupos.toArray());
        jTable1.setModel(tableModelGrupo);
        if (!grupos.isEmpty())
            jTable1.setRowSelectionInterval(0,0);

    }

    private Integer getPosicao(Grupo marca){
        try {
            if (marca.getId()== null)
                marca = new GrupoService().getLast();
        } catch (Exception e) {
            e.printStackTrace();
        }

        Integer tam = grupos.size();
        Integer pos = 0;
        boolean achou =false;
        while ( pos < tam && !achou ){
            if (grupos.get(pos).getId().equals(marca.getId())) {
                achou =true;
            } else
                pos++;
        }
        return pos;
    }

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {
        CadastrarGrupoForm.Callback callback = (marca -> {
            try {
                grupos = new GrupoService().getAll("");
            } catch (Exception ex){
                System.out.println(ex);
            }
            tableModelGrupo.setList(grupos.toArray());
            jTable1.setModel(tableModelGrupo);

            if (!grupos.isEmpty()) {
                jTable1.setRowSelectionInterval(getPosicao(marca), getPosicao(marca));
            }
        });
        cadastrarGrupoForm  = new CadastrarGrupoForm(getWindowParent(), true, new Grupo(), callback);
        cadastrarGrupoForm.desbloqueiaedt();
        cadastrarGrupoForm.show();
    }

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {
        if (jTable1.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "Selecione um registro para continuar");
            return;
        }
        CadastrarGrupoForm.Callback callback = (marca -> {
            try {
                grupos = new GrupoService().getAll("");
            } catch (Exception ex){
                System.out.println(ex);
            }
            tableModelGrupo.setList(grupos.toArray());

            if (!grupos.isEmpty()) {
                jTable1.setRowSelectionInterval(getPosicao(marca), getPosicao(marca));
            }
        });
        grupoSelecionado=grupos.get(jTable1.getSelectedRow());
        cadastrarGrupoForm=new CadastrarGrupoForm(getWindowParent(),false, grupoSelecionado,callback);
        cadastrarGrupoForm.carregaEdt();
        cadastrarGrupoForm.show();
    }

    private void btnVisualizarActionPerformed(java.awt.event.ActionEvent evt) {
        if (jTable1.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "Selecione um registro para continuar");
            return;
        }
        grupoSelecionado=grupos.get(jTable1.getSelectedRow());
        cadastrarGrupoForm=new CadastrarGrupoForm(this.getWindowParent(),false, new Grupo(), null);
        cadastrarGrupoForm.setGrupo(grupoSelecionado);
        cadastrarGrupoForm.carregaEdt();
        cadastrarGrupoForm.bloqueiaedt();
        cadastrarGrupoForm.show();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluirDesativar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnVisualizar;
    private javax.swing.JTextField edtPesquisa;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
