/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.grupo;

import gui.modeltable.TableModelGrupo;
import gui.swing.DialogPadrao;
import lib.model.grupo.Grupo;
import lib.model.interno.ModuloSistema;
import lib.model.interno.NivelAcessoModulo;
import lib.service.GrupoService;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.util.List;

/**
 *
 * @author diego.lenz
 */
public class PesquisarGrupo extends DialogPadrao {
    private TableModelGrupo tableModelGrupo;
    private PesquisarGrupo.Callback callback;
    private List<Grupo> grupos;
    private GrupoService grupoService;
    private CadastrarGrupoForm cadastrarGrupoForm;
    private Grupo grupoSelecionado;

    /**
     * Creates new form Pesquisar
     */

    public interface Callback {

        void handle(Grupo pessoa);
    }

    public PesquisarGrupo(Window parent, boolean modal, PesquisarGrupo.Callback callBack) {
        super( parent, modal, ModuloSistema.GRUPOS_PRODUTOS_SERVICOS, NivelAcessoModulo.SOMENTE_LEITURA);
        this.callback=callBack;
        initComponents();
        this.grupoService = new GrupoService();
        this.tableModelGrupo = new TableModelGrupo();
        this.btnpesquisarActionPerformed(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        edtpesquisa = new javax.swing.JFormattedTextField();
        btnpesquisar = new javax.swing.JToggleButton();
        btnselecionar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        btnNovo = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluirDesativar = new javax.swing.JButton();
        btnVisualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta grupo");
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setModal(true);
        setResizable(false);

        btnpesquisar.setText("Pesquisar");
        btnpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpesquisarActionPerformed(evt);
            }
        });

        btnselecionar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnselecionar.setText("selecionar");
        btnselecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnselecionarActionPerformed(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabela.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tabela);

        btnNovo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnAlterar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAlterar.setText("alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluirDesativar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExcluirDesativar.setText("excluir");
        btnExcluirDesativar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirDesativarActionPerformed(evt);
            }
        });

        btnVisualizar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnVisualizar.setText("Visualizar");
        btnVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVisualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluirDesativar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnselecionar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(edtpesquisa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnselecionar)
                    .addComponent(btnNovo)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluirDesativar)
                    .addComponent(btnVisualizar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnpesquisarActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            grupos = grupoService.getAll(edtpesquisa.getText());
        } catch (Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        tableModelGrupo.setList(this.grupos.toArray());
        tabela.setModel(tableModelGrupo);
        if (grupos.isEmpty()) {
            if (evt != null)
                JOptionPane.showMessageDialog(this, "Nenhum resultado foi retornado");
        }else
            tabela.setRowSelectionInterval(0,0);
    }

    private Integer getPosicao(Grupo marca){
        try {
            if (marca.getId() == null)
                marca = new GrupoService().getLast();
        } catch (Exception e) {
            e.printStackTrace();
        }

        Integer tam = grupos.size();
        Integer pos = 0;
        boolean achou =false;
        while ( pos < tam && !achou ){
            if (grupos.get(pos).getId().equals(marca.getId())) {
                achou =true;
            } else
                pos++;
        }
        return pos;
    }

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {
        CadastrarGrupoForm.Callback callback = (marca -> {
            try {
                grupos = new GrupoService().getAll("");
            } catch (Exception ex){
                System.out.println(ex);
            }
            tableModelGrupo.setList(grupos.toArray());

            if (!grupos.isEmpty()) {
                tabela.setRowSelectionInterval(getPosicao(marca), getPosicao(marca));
            }
        });
        cadastrarGrupoForm  = new CadastrarGrupoForm(this, true, new Grupo(), callback);
        cadastrarGrupoForm.desbloqueiaedt();
        cadastrarGrupoForm.show();
    }

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {
        if (tabela.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "Selecione um registro para continuar");
            return;
        }
        CadastrarGrupoForm.Callback callback = (marca -> {
            try {
                grupos = new GrupoService().getAll("");
            } catch (Exception ex){
                System.out.println(ex);
            }
            tableModelGrupo.setList(grupos.toArray());

            if (!grupos.isEmpty()) {
                tabela.setRowSelectionInterval(getPosicao(marca), getPosicao(marca));
            }
        });
        grupoSelecionado=grupos.get(tabela.getSelectedRow());
        cadastrarGrupoForm=new CadastrarGrupoForm(this,false, grupoSelecionado,callback);
        cadastrarGrupoForm.setGrupo(this.grupoSelecionado);
        cadastrarGrupoForm.carregaEdt();
        cadastrarGrupoForm.desbloqueiaedt();
        cadastrarGrupoForm.show();
    }

    private void btnVisualizarActionPerformed(java.awt.event.ActionEvent evt) {
        if (tabela.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "Selecione um registro para continuar");
            return;
        }
        grupoSelecionado=grupos.get(tabela.getSelectedRow());
        cadastrarGrupoForm=new CadastrarGrupoForm(this,false, new Grupo(), null);
        cadastrarGrupoForm.setGrupo(grupoSelecionado);
        cadastrarGrupoForm.carregaEdt();
        cadastrarGrupoForm.bloqueiaedt();
        cadastrarGrupoForm.show();
    }


    private void btnselecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnselecionarActionPerformed
        if (tabela.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this , "Nenhuma pessoa selecionada");
            return;
        } else {
            Integer id=(Integer)this.tabela.getValueAt(this.tabela.getSelectedRow(),0);
            grupoSelecionado = grupos.get(this.tabela.getSelectedRow());
            callback.handle(grupoSelecionado);
            this.dispose();
        }
    }//GEN-LAST:event_btnselecionarActionPerformed


    private void btnExcluirDesativarActionPerformed(ActionEvent evt) {
        if (tabela.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "Selecione um registro para continuar");
            return;
        }
        grupoSelecionado=grupos.get(tabela.getSelectedRow());
        CadastrarGrupoForm cadastrarGrupoForm = new CadastrarGrupoForm(getWindowParent(), true, grupoSelecionado, null);
        cadastrarGrupoForm.carregaEdt();
        cadastrarGrupoForm.bloqueiaedt();
        cadastrarGrupoForm.show();
        try {
            grupoService.deleteByID(grupoSelecionado.getId());
            if (JOptionPane.showConfirmDialog(this, "Deseja realmente excluir o grupo selecionado ?", "Atenção", JOptionPane.YES_NO_OPTION) != 0) {
                cadastrarGrupoForm.dispose();
                return;
            }
            JOptionPane.showMessageDialog(this, "Excluido com sucesso");

        } catch (Exception e) {
            if (JOptionPane.showConfirmDialog(this,"Não é possivel excluir o registro, deseja desativa-lo?", "ATENÇÂO", JOptionPane.YES_NO_OPTION)==0) {
                if (!grupoSelecionado.getAtivo())
                    JOptionPane.showMessageDialog(this, "Pessoa já está desativada");
                try {
                    grupoService.update(grupoSelecionado);
                    JOptionPane.showMessageDialog(this,
                            "Desativado com sucesso"
                    );
                    grupos = new GrupoService().getAll("");
                } catch (Exception e1) {
                    JOptionPane.showMessageDialog(this, "Não foi possivel desativar");
                }
            }
        }
        try {
            grupos = new GrupoService().getAll("");
        } catch (Exception ex){}
        tableModelGrupo.setList(grupos.toArray());
        tabela.setModel(tableModelGrupo);
        cadastrarGrupoForm.dispose();
    }



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesquisarGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesquisarGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesquisarGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesquisarGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PesquisarGrupo dialog = new PesquisarGrupo(new javax.swing.JFrame(), true,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluirDesativar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnVisualizar;
    private javax.swing.JToggleButton btnpesquisar;
    private javax.swing.JButton btnselecionar;
    private javax.swing.JFormattedTextField edtpesquisa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
