/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.pessoas.clientes;

import gui.modeltable.TableModelPessoa;

import gui.swing.DialogPadrao;
import lib.model.interno.ModuloSistema;
import lib.model.interno.NivelAcessoModulo;
import lib.model.pessoa.Pessoa;
import lib.model.pessoa.cliente.Cliente;
import lib.service.ClienteService;
//import sun.plugin2.jvm.RemoteJVMLauncher;

import javax.swing.*;
import java.awt.*;
import java.util.List;

/**
 *
 * @author diego.lenz
 */
public class PesquisarCliente extends DialogPadrao {
    private Cliente pessoaSelecionada=null;
    private TableModelPessoa modelo;
    private PesquisarCliente.Callback callback;
    private List<Cliente> list;
    private ClienteService clienteService = new ClienteService();

    /**
     * Creates new form Pesquisar
     */

    public interface Callback {

        void handle(Cliente pessoa);
    }

    public PesquisarCliente(Window parent, boolean modal, PesquisarCliente.Callback callBack) {
        super( parent, modal, ModuloSistema.CLIENTES, NivelAcessoModulo.SOMENTE_LEITURA);
        this.callback=callBack;
        initComponents();
        modelo =new TableModelPessoa();
        btnpesquisarActionPerformed(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        edtpesquisa = new javax.swing.JFormattedTextField();
        btnpesquisar = new javax.swing.JToggleButton();
        btnselecionar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        btnnovapessoa = new javax.swing.JButton();
        btnalt = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisar pessoa");
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setModal(true);

        btnpesquisar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnpesquisar.setText("Pesquisar");
        btnpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpesquisarActionPerformed(evt);
            }
        });

        btnselecionar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnselecionar.setText("selecionar");
        btnselecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnselecionarActionPerformed(evt);
            }
        });

        tabela.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabela.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tabela);

        btnnovapessoa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnnovapessoa.setText("Nova pessoa");
        btnnovapessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnovapessoaActionPerformed(evt);
            }
        });

        btnalt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnalt.setText("alterar");
        btnalt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaltActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExcluir.setText("excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(edtpesquisa)
                        .addGap(2, 2, 2)
                        .addComponent(btnpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnnovapessoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnalt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnselecionar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnalt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnnovapessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnselecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (tabela.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "Selecione um registro para continuar");
            return;
        }
        Cliente pessoaSelecionado=list.get(tabela.getSelectedRow());
        NovoClienteForm novoClienteForm = new NovoClienteForm(this, true, pessoaSelecionado);
        novoClienteForm.carregaredt();
        novoClienteForm.bloqueiaedt();
        novoClienteForm.show();
        if (JOptionPane.showConfirmDialog(novoClienteForm,"Deseja realmente excluir o cliente selecionado ?", "Atenção", JOptionPane.YES_NO_OPTION) !=0)
            return;

        try {
            new ClienteService().deleteByID(pessoaSelecionado);
            JOptionPane.showMessageDialog(this, "Excluido com sucesso");
        }catch (Exception e) {
            if (JOptionPane.showConfirmDialog(this,"Não é possivel excluir o registro, deseja desativa-lo?", "ATENÇÂO", JOptionPane.YES_NO_OPTION)==0) {
                if (!pessoaSelecionado.getAtivo())
                    JOptionPane.showMessageDialog(this, "Pessoa já está desativada");
                try {
                    new ClienteService().update(pessoaSelecionado);
                    JOptionPane.showMessageDialog(this,
                            "Desativado com sucesso"
                    );
                } catch (Exception e1) {
                    JOptionPane.showMessageDialog(this, "Não foi possivel desativar");
                }
            }
        }
        try {
            list = new ClienteService().getAll(edtpesquisa.getText());
        } catch (Exception e){
            JOptionPane.showConfirmDialog(this,"Falha ao retornar dados, contate o adminstrador do sistema \n" + e.getMessage());
        }
        modelo.setList(list.toArray());
        tabela.setModel(modelo);
        novoClienteForm.dispose();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnaltActionPerformed(java.awt.event.ActionEvent evt) {
        if (tabela.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "Selecione um registro para continuar");
            return;
        }
        pessoaSelecionada=list.get(tabela.getSelectedRow());
        NovoClienteForm novapessoa=new NovoClienteForm(this,false, pessoaSelecionada);
        novapessoa.carregaredt();
        novapessoa.desbloqueiaedt();
        novapessoa.show();
    }

    private void btnpesquisarActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            list= clienteService.getAllClientesAtivos(edtpesquisa.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        modelo.setList(list.toArray());
        tabela.setModel(modelo);
        if (list.isEmpty()){
            if (evt!=null)
                JOptionPane.showMessageDialog(this, "Nenhum resultado enconstrado");
        } else tabela.setRowSelectionInterval(0,0);
    }

    private void btnselecionarActionPerformed(java.awt.event.ActionEvent evt) {
        //PessoaCotaDao pdao=new PessoaCotaDao();
        if (tabela.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this , "Nenhuma pessoa Cselecionada");
            return;
        } else {
            pessoaSelecionada = list.get(tabela.getSelectedRow());
            if (!pessoaSelecionada.getAtivo()){
                JOptionPane.showMessageDialog(this, "Cliente selecionado não esta ativo");
            }
            callback.handle(pessoaSelecionada);
            this.dispose();
        }
    }                                             

    private void btnnovapessoaActionPerformed(java.awt.event.ActionEvent evt) {
        NovoClienteForm novapessoa=new NovoClienteForm(this, true, new Cliente());
        novapessoa.show();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnalt;
    private javax.swing.JButton btnnovapessoa;
    private javax.swing.JToggleButton btnpesquisar;
    private javax.swing.JButton btnselecionar;
    private javax.swing.JFormattedTextField edtpesquisa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
