/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.pessoas.fornecedores;

import gui.modeltable.TableModelFornecedor;
import gui.swing.SociusTab;
import gui.swing.WindowPadrao;
import lib.dao.imp.pessoa.FornecedorDao;
import lib.model.interno.ModuloSistema;
import lib.model.pessoa.fornecedor.Fornecedor;
import lib.service.FornecedorService;

import javax.swing.*;
import java.awt.*;
import java.util.List;

/**
 *
 * @author Diego
 */
public class ConsultaFornecedoresForm extends SociusTab implements WindowPadrao {
    private Fornecedor pessoaSelecionada;
    private List<Fornecedor> pessoas;
    private FornecedorDao pessoadao=new FornecedorDao();
    private CadastroFornecedorForm novoPessoaForm;
    private TableModelFornecedor modeloTabela;


    /**
     * Creates new form ConsultaPanel
     */
    public ConsultaFornecedoresForm(Window parent) {
        super(parent, ModuloSistema.FORNECEDORES);
        initComponents();
        initTabela();
        jButton1ActionPerformed(null);
    }

    public void initTabela(){
        modeloTabela = new TableModelFornecedor();
        jTable1.setModel(modeloTabela);
        this.jTable1.getColumnModel().getColumn(0).setPreferredWidth(30);
        this.jTable1.getColumnModel().getColumn(1).setPreferredWidth(250);
        this.jTable1.getColumnModel().getColumn(2).setPreferredWidth(80);
        this.jTable1.getColumnModel().getColumn(3).setPreferredWidth(100);
        this.jTable1.getColumnModel().getColumn(4).setPreferredWidth(100);
        this.jTable1.getColumnModel().getColumn(5).setPreferredWidth(50);
        this.jTable1.getColumnModel().getColumn(6).setPreferredWidth(150);
        this.jTable1.getColumnModel().getColumn(7).setPreferredWidth(150);
        this.jTable1.getColumnModel().getColumn(8).setPreferredWidth(50);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        edtPesquisa = new javax.swing.JTextField();
        btnVisualizar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setName("Consulta"); // NOI18N

        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(5);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(10);
        }

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnVisualizar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnVisualizar.setText("Visualizar");
        btnVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarActionPerformed(evt);
            }
        });

        btnNovo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnAlterar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(edtPesquisa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVisualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(edtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnVisualizar)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir))
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        pessoaSelecionada = pessoas.get(jTable1.getSelectedRow());
        CadastroFornecedorForm cadastroFornecedorForm = new CadastroFornecedorForm(getWindowParent(), true, pessoaSelecionada );
        cadastroFornecedorForm.carregaredt();
        cadastroFornecedorForm.bloqueiaedt();
        cadastroFornecedorForm.show();
        if (JOptionPane.showConfirmDialog(this, "Deseja realmente excluir o fornecedor " + pessoaSelecionada.getNome() + " ?","ATENÇÃO", JOptionPane.YES_NO_OPTION) == 0 ){
            try {
                new FornecedorService().deleteByID(pessoaSelecionada);
                JOptionPane.showMessageDialog(this, "Fornecedor excluido com sucesso");
                cadastroFornecedorForm.dispose();
                return;
            }catch (Exception ex){
                if (pessoaSelecionada.getAtivo()) {
                    if (JOptionPane.showConfirmDialog(this, "O fornecedor ja possui operações relacionadas a ele, dejesa desastiva-lo ?", "Atenção", JOptionPane.YES_NO_OPTION) == 0) {
                        pessoaSelecionada.setAtivo(false);
                        try {
                            new FornecedorService().update(pessoaSelecionada);
                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(this, "Não foi possivel desativar " + e.getMessage());
                        }
                    }
                }

            }
        }
        try {
            pessoas = pessoadao.getAllFornecedores("");
            modeloTabela.setList(pessoas.toArray());
        } catch (Exception ex){
            JOptionPane.showMessageDialog(this,  ex.getMessage());
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            pessoas = pessoadao.getAllFornecedores(edtPesquisa.getText());
        } catch (Exception e) {
           JOptionPane.showMessageDialog(this,  e.getMessage());
        }
        modeloTabela.setList(pessoas.toArray());
        if (pessoas.isEmpty() && evt!=null )
            JOptionPane.showMessageDialog(this,"Nenhum resultado encontrado");
        else if (!pessoas.isEmpty()) this.jTable1.setRowSelectionInterval(0,0);
    }

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {
        Fornecedor pessoa=new Fornecedor();
        CadastroFornecedorForm novoPessoaForm = new CadastroFornecedorForm(getWindowParent(), true, pessoa);
        novoPessoaForm.show();
    }

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {
        if (jTable1.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "Selecione um registro para continuar");
            return;
        }
        pessoaSelecionada=pessoas.get(jTable1.getSelectedRow());
        novoPessoaForm=new CadastroFornecedorForm(getWindowParent(),false, pessoaSelecionada);
        novoPessoaForm.carregaredt();
        novoPessoaForm.desbloqueiaedt();
        novoPessoaForm.show();
    }

    private void btnVisualizarActionPerformed(java.awt.event.ActionEvent evt) {
        if (jTable1.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "Selecione um registro para continuar");
            return;
        }
        pessoaSelecionada=pessoas.get(jTable1.getSelectedRow());
        novoPessoaForm=new CadastroFornecedorForm(getWindowParent(),false, pessoaSelecionada);
        novoPessoaForm.carregaredt();
        novoPessoaForm.bloqueiaedt();
        novoPessoaForm.show();
    }

    public List<Fornecedor> getPessoas() {
        return pessoas;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnVisualizar;
    private javax.swing.JTextField edtPesquisa;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
