/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.operador;
import gui.enderecos.cidades.PesquisarCidade;
import gui.swing.SwingFormatterFactory;
import javafx.scene.input.KeyCode;
import lib.dao.imp.sistema.FuncionarioDao;
import lib.model.endereco.cidade.Cidade;
import lib.model.interno.Funcionario;
import lib.model.interno.GrupoFuncionario;
import lib.model.pessoa.Sexo;
import lib.model.pessoa.TipoPessoa;
import lib.service.CidadeService;

import javax.swing.*;
import java.awt.*;
import java.util.*;
import java.util.List;

/**
 *
 * @author diego.lenz
 */
public class CadastrarFuncionario extends javax.swing.JDialog {

    private String senha;
    private final boolean modoAdicao;
    private final Funcionario operador;
    private FuncionarioDao operadorDao;
    private final Map<GrupoFuncionario, JCheckBox> grupos;


    private void initGrupos() {
     /*   new TipoOperadorDao().listar()
                .stream()
                .sorted(Comparator.comparing(TipoOperador::getDescricao))
                .forEach(item -> {
                    boolean selecionado = operador.getGrupos()
                            .stream()
                            .filter(registro -> registro.getTipo().equals(item))
                            .findAny()
                            .isPresent();

                    JCheckBox checkBox = new JCheckBox(item.getDescricao());
                    checkBox.setBackground(Color.WHITE);
                    checkBox.setSelected(selecionado);

                    grupos.put(item, checkBox);
                    pnlPermissoes.add(checkBox);

                });

        pnlPermissoes.revalidate(); */
}

    public CadastrarFuncionario(java.awt.Frame parent, boolean modal, Funcionario operador) {
        super(parent, modal);
        initComponents();
        if (operador==null){
            operador=new Funcionario();
        }
        this.operador = operador;
        modoAdicao = operador.getId() == null;
        if (operador.getGrupos()==null){
            List<GrupoFuncionario> grupo=new ArrayList<>();
            operador.setGrupos( grupo);
        }
        grupos = new HashMap<GrupoFuncionario, JCheckBox>();

        this.initGrupos();
    }

    public CadastrarFuncionario(Frame parent, boolean modal) {
        this(parent, modal, new Funcionario());
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane5 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblTitulo = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        pnlPrincipal = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        cmbtipocad = new javax.swing.JComboBox<>();
        edtCodigo = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtApelidoNomeFantasia = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtTel = new javax.swing.JTextField();
        cmbSexo = new javax.swing.JComboBox<>();
        txtTelOpcional = new javax.swing.JTextField();
        txtCpf = new javax.swing.JFormattedTextField();
        txtDtNasc = new com.toedter.calendar.JDateChooser();
        edtCidade = new javax.swing.JTextField();
        edtCodCidade = new javax.swing.JTextField();
        btnAltCidade = new javax.swing.JButton();
        edtEstado = new javax.swing.JTextField();
        edtPais = new javax.swing.JTextField();
        edtbairro = new javax.swing.JTextField();
        edtCep = new javax.swing.JFormattedTextField(
            SwingFormatterFactory.buildCep()
        );
        edtLogradouro = new javax.swing.JTextField();
        edtDtCadastro = new javax.swing.JTextField();
        edtDtUltAtualizacao = new javax.swing.JTextField();
        spnNum = new javax.swing.JSpinner();
        txtRg = new javax.swing.JFormattedTextField();
        pnlContainerPermissoes = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pnlPermissoes = new javax.swing.JPanel();
        edtUsuario = new javax.swing.JTextField();
        edtSenha = new javax.swing.JTextField();
        lblTitulo1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setModal(true);
        setResizable(false);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitulo.setText("Novo operador");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        pnlPrincipal.setToolTipText("");
        pnlPrincipal.setName(""); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setAutoscrolls(true);
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        cmbtipocad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbtipocad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FISICA", "JURIDICA", "ESTRANGEIRO" }));
        cmbtipocad.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo de cadastro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        cmbtipocad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbtipocadActionPerformed(evt);
            }
        });

        edtCodigo.setEditable(false);
        edtCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edtCodigo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Código", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        txtNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNome.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nome *", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        txtApelidoNomeFantasia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtApelidoNomeFantasia.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Apelido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtEmail.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Email", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        txtTel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Telefone *", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        cmbSexo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        cmbSexo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sexo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        txtTelOpcional.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTelOpcional.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Telefone Opcional", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        txtCpf.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CPF *", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfActionPerformed(evt);
            }
        });

        txtDtNasc.setBackground(new java.awt.Color(255, 255, 255));
        txtDtNasc.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data de nascimento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        edtCidade.setEditable(false);
        edtCidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edtCidade.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CIDADE *", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        edtCodCidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edtCodCidade.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cód. da cidade", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        edtCodCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtCodCidadeKeyPressed(evt);
            }
        });

        btnAltCidade.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnAltCidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pesquisar.png"))); // NOI18N
        btnAltCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltCidadeActionPerformed(evt);
            }
        });

        edtEstado.setEditable(false);
        edtEstado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edtEstado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Estado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        edtEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtEstadoActionPerformed(evt);
            }
        });

        edtPais.setEditable(false);
        edtPais.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edtPais.setBorder(javax.swing.BorderFactory.createTitledBorder("PAÍS"));

        edtbairro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edtbairro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bairro *", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        edtCep.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CEP *", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        try {
            edtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        edtCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtCepActionPerformed(evt);
            }
        });

        edtLogradouro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edtLogradouro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Logradouro *", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        edtDtCadastro.setEditable(false);
        edtDtCadastro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dt. de cadastro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        edtDtUltAtualizacao.setEditable(false);
        edtDtUltAtualizacao.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dt. Ultm. alteração", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        spnNum.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Numero *", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        txtRg.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RG *", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        try {
            txtRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtRg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(edtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbtipocad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(edtDtCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(edtDtUltAtualizacao, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(edtCodCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(edtbairro, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(edtCidade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtTelOpcional, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(edtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnAltCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(edtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(edtPais, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(spnNum, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(edtLogradouro)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome)
                            .addComponent(txtApelidoNomeFantasia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDtNasc, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(txtCpf))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRg)
                            .addComponent(cmbSexo, 0, 140, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(cmbtipocad, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtDtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(cmbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApelidoNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelOpcional, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(edtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(edtPais, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(edtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(edtCodCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAltCidade)
                        .addGap(2, 2, 2)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnNum)
                    .addComponent(edtLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(edtDtCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(edtDtUltAtualizacao, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pnlPrincipal.addTab("Informações Pessoais", jPanel1);

        pnlContainerPermissoes.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(null);

        pnlPermissoes.setLayout(new javax.swing.BoxLayout(pnlPermissoes, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane2.setViewportView(pnlPermissoes);

        edtUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Usúario"));

        edtSenha.setBorder(javax.swing.BorderFactory.createTitledBorder("Senha"));

        lblTitulo1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitulo1.setText("Grupos");

        javax.swing.GroupLayout pnlContainerPermissoesLayout = new javax.swing.GroupLayout(pnlContainerPermissoes);
        pnlContainerPermissoes.setLayout(pnlContainerPermissoesLayout);
        pnlContainerPermissoesLayout.setHorizontalGroup(
            pnlContainerPermissoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContainerPermissoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlContainerPermissoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addGroup(pnlContainerPermissoesLayout.createSequentialGroup()
                        .addComponent(lblTitulo1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlContainerPermissoesLayout.createSequentialGroup()
                        .addComponent(edtUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlContainerPermissoesLayout.setVerticalGroup(
            pnlContainerPermissoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContainerPermissoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlContainerPermissoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlPrincipal.addTab("Informações do usuario", pnlContainerPermissoes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar))
                    .addComponent(lblTitulo)
                    .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void carregar(){
        operador.setUsuario(edtUsuario.getText());
        operador.setSenha(edtSenha.getText());
        operador.setNome(this.txtNome.getText());
        operador.setCpfCnpj(txtCpf.getText());
        operador.setDataNascimento(this.txtDtNasc.getDate());
        operador.setRgIe(txtRg.getText());
        operador.setNomeFantasia_Apelido(txtApelidoNomeFantasia.getText());
        operador.setSexo((Sexo) cmbSexo.getSelectedItem());

        if (cmbtipocad.getSelectedItem() == "FISICA") {
            operador.setTipo(TipoPessoa.FISICA);
        } else if (cmbtipocad.getSelectedItem() == "JURIDICA") {
            operador.setTipo(TipoPessoa.JURIDICA);
        } else operador.setTipo(TipoPessoa.ESTRANGEIRO);

        operador.setTelefone(this.txtTel.getText());
        operador.setTelefoneAlternativo(this.txtTelOpcional.getText());
        operador.setEmail(txtEmail.getText());

       // operador.setNumeroResidencial();
        operador.setBairro(edtbairro.getText());
        operador.setCep(edtCep.getText());
        operador.setLogradouro(edtLogradouro.getText());

        if (operador.getId()==null)
            operador.setDataCadastro(new Date());
        operador.setDataUltAlteracao(new Date());
        operador.setAtivo(true);
    }

    public void carregaredt(){
        edtUsuario.setText(operador.getUsuario());
        edtSenha.setText(operador.getSenha());
        edtCodigo.setText(operador.getId().toString());
        txtNome.setText(operador.getNome());
        txtRg.setText(operador.getRgIe());
        this.edtCodigo.setText(operador.getId().toString());
        txtCpf.setText(operador.getCpfCnpj());
        txtApelidoNomeFantasia.setText(operador.getNomeFantasia_Apelido());
        txtTel.setText(operador.getTelefone());
        txtTelOpcional.setText(operador.getTelefoneAlternativo());
        txtEmail.setText(operador.getEmail());
        txtDtNasc.setDate(operador.getDataNascimento());
        edtDtUltAtualizacao.setText(operador.getDataUltAlteracao().toString());
        edtDtCadastro.setText(operador.getDataCadastro().toString());

            edtCidade.setText(this.operador.getCidade().getNome());
            edtCodCidade.setText(this.operador.getCidade().getId().toString());
            edtEstado.setText(this.operador.getCidade().getEstado().getNome());
            edtPais.setText(this.operador.getCidade().getEstado().getPais().getNome());
            edtLogradouro.setText(this.operador.getLogradouro());
            edtbairro.setText(this.operador.getBairro());
            edtCep.setText(this.operador.getCep());
            spnNum.setValue(this.operador.getNumeroResidencial());

        cmbSexo.setSelectedItem(operador.getSexo());
        cmbtipocad.setSelectedItem(operador.getTipo());
    }


    public void bloqueiaedt(){
        this.txtCpf.setEditable(false);
        this.txtNome.setEditable(false);
        this.txtTel.setEditable(false);
        this.txtRg.setEditable(false);
        this.cmbSexo.setEnabled(false);
        this.cmbtipocad.setEnabled(false);
        this.txtTelOpcional.setEditable(false);
        txtEmail.setEnabled(false);
        this.edtCep.setEnabled(false);
        this.edtCodigo.setEnabled(false);
        this.edtLogradouro.setEnabled(false);
        this.edtCodCidade.setEnabled(false);
        this.txtApelidoNomeFantasia.setEnabled(false);
    }

    public void desbloqueiaedt(){
        this.txtCpf.setEditable(true);
        this.txtNome.setEditable(true);
        this.txtTel.setEditable(true);
        this.txtRg.setEditable(true);
        this.cmbSexo.setEnabled(true);
        this.txtTelOpcional.setEditable(true);
        this.cmbtipocad.setEnabled(true);
        txtEmail.setEnabled(true);

    }
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt)  {//GEN-FIRST:event_btnSalvarActionPerformed
        carregar();
        FuncionarioDao operadorDao = new FuncionarioDao();

        if (modoAdicao) {
            operador.setDataCadastro(new Date());
            operador.setSenha(senha);
        }

        if (operador.getNome() == null || operador.getNome().trim().isEmpty()) {
            JOptionPane.showMessageDialog(
                    null,
                    "Nenhum nome foi informado para o operador"
            );
            return;
        }



       /* ValidacaoFacade.Resultado resultado = ValidacaoFacade.validar(operador);
        if (resultado.isValoresInvalidos()) {
            JOptionPane.showMessageDialog(this,
                    "Os seguintes problemas foram encontrados:\n" + resultado.getMensagem()
            );
            return;
        } */
        if (modoAdicao) {
            Funcionario testeUsuario = null;//(Operador) operadorDao.getByUsuarioExato(operador.getUsuario());
            if (testeUsuario != null) {
                JOptionPane.showMessageDialog(this,
                        "Usuario ja cadastrado, tente novamente");
                return;
            }

            testeUsuario = null;//(Operador) operadorDao.getByCpf(operador.getUsuario());
            if (testeUsuario != null) {
                JOptionPane.showMessageDialog(this,
                        "Cpf ja cadastrado!");
                return;
            }
        }


            try {

            } catch (Throwable ex) {
                JOptionPane.showMessageDialog(this,
                        ex.getMessage());
                return;
            }

            JOptionPane.showMessageDialog(this,
                "Operador salvo com sucesso!");
            dispose();


    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        boolean cancelar;
        if ( JOptionPane.showConfirmDialog
                (this, "Tem certeza de que deseja cancelar?","Cancelar ", JOptionPane.YES_NO_OPTION )==1){
             cancelar = false;
        } else cancelar=true;

        if (cancelar) {
            this.dispose();
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cmbtipocadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbtipocadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbtipocadActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfActionPerformed

    private void edtCodCidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtCodCidadeKeyPressed
        if (evt.getKeyCode() == KeyCode.ENTER.impl_getCode()) {
            try {
                CidadeService cidadeService =new CidadeService();
                this.operador.setCidade((Cidade) cidadeService.getCidadeByID(Integer.parseInt(edtCodCidade.getText())));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
            if ( this.operador.getCidade() != null){
                this.edtCidade.setText(this.operador.getCidade().getNome());
                this.edtEstado.setText(this.operador.getCidade().getEstado().getNome());
                this.edtPais.setText(this.operador.getCidade().getEstado().getPais().getNome());
            }
        }
    }//GEN-LAST:event_edtCodCidadeKeyPressed

    private void btnAltCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltCidadeActionPerformed
        PesquisarCidade.Callback callback = (cidade -> {
            if (cidade!=null){
                operador.setCidade(cidade);
                edtCidade.setText(cidade.getNome());
                edtCodCidade.setText(cidade.getId().toString());
                edtPais.setText(cidade.getEstado().getPais().getNome());
                edtEstado.setText(cidade.getEstado().getNome());
            }
        });
        new PesquisarCidade(this, true, callback).show();
    }//GEN-LAST:event_btnAltCidadeActionPerformed

    private void edtEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtEstadoActionPerformed

    private void txtRgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRgActionPerformed

    private void edtCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtCepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtCepActionPerformed

    public String getSenha() {
        return senha;
    }

    public void setSenha(String senha) {
        this.senha = senha;
        edtSenha.setText(senha);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastrarFuncionario dialog = new CadastrarFuncionario(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAltCidade;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cmbSexo;
    private javax.swing.JComboBox<String> cmbtipocad;
    private javax.swing.JFormattedTextField edtCep;
    private javax.swing.JTextField edtCidade;
    private javax.swing.JTextField edtCodCidade;
    private javax.swing.JTextField edtCodigo;
    private javax.swing.JTextField edtDtCadastro;
    private javax.swing.JTextField edtDtUltAtualizacao;
    private javax.swing.JTextField edtEstado;
    private javax.swing.JTextField edtLogradouro;
    private javax.swing.JTextField edtPais;
    private javax.swing.JTextField edtSenha;
    private javax.swing.JTextField edtUsuario;
    private javax.swing.JTextField edtbairro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JPanel pnlContainerPermissoes;
    private javax.swing.JPanel pnlPermissoes;
    private javax.swing.JTabbedPane pnlPrincipal;
    private javax.swing.JSpinner spnNum;
    private javax.swing.JTextField txtApelidoNomeFantasia;
    private javax.swing.JFormattedTextField txtCpf;
    private com.toedter.calendar.JDateChooser txtDtNasc;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JFormattedTextField txtRg;
    private javax.swing.JTextField txtTel;
    private javax.swing.JTextField txtTelOpcional;
    // End of variables declaration//GEN-END:variables
}
